/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSTATEMACHINE_H
#define _MOCKSTATEMACHINE_H

#include "StateMachine.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockStateMachine_Init(void);
void MockStateMachine_Destroy(void);
void MockStateMachine_Verify(void);




#define StateMachine_Init_IgnoreAndReturn(cmock_retval) StateMachine_Init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void StateMachine_Init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
#define StateMachine_Init_ExpectAnyArgsAndReturn(cmock_retval) StateMachine_Init_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void StateMachine_Init_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
#define StateMachine_Init_ExpectAndReturn(cmock_retval) StateMachine_Init_CMockExpectAndReturn(__LINE__, cmock_retval)
void StateMachine_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
typedef ErrorCode_t (* CMOCK_StateMachine_Init_CALLBACK)(int cmock_num_calls);
void StateMachine_Init_StubWithCallback(CMOCK_StateMachine_Init_CALLBACK Callback);
#define StateMachine_Run_IgnoreAndReturn(cmock_retval) StateMachine_Run_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void StateMachine_Run_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
#define StateMachine_Run_ExpectAnyArgsAndReturn(cmock_retval) StateMachine_Run_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void StateMachine_Run_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
#define StateMachine_Run_ExpectAndReturn(cmock_retval) StateMachine_Run_CMockExpectAndReturn(__LINE__, cmock_retval)
void StateMachine_Run_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
typedef ErrorCode_t (* CMOCK_StateMachine_Run_CALLBACK)(int cmock_num_calls);
void StateMachine_Run_StubWithCallback(CMOCK_StateMachine_Run_CALLBACK Callback);
#define StateMachine_Enter_NRE_Ignore() StateMachine_Enter_NRE_CMockIgnore()
void StateMachine_Enter_NRE_CMockIgnore(void);
#define StateMachine_Enter_NRE_ExpectAnyArgs() StateMachine_Enter_NRE_CMockExpectAnyArgs(__LINE__)
void StateMachine_Enter_NRE_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define StateMachine_Enter_NRE_Expect(enteringNewState) StateMachine_Enter_NRE_CMockExpect(__LINE__, enteringNewState)
void StateMachine_Enter_NRE_CMockExpect(UNITY_LINE_TYPE cmock_line, bool_t enteringNewState);
typedef void (* CMOCK_StateMachine_Enter_NRE_CALLBACK)(bool_t enteringNewState, int cmock_num_calls);
void StateMachine_Enter_NRE_StubWithCallback(CMOCK_StateMachine_Enter_NRE_CALLBACK Callback);
#define StateMachine_Enter_NRE_IgnoreArg_enteringNewState() StateMachine_Enter_NRE_CMockIgnoreArg_enteringNewState(__LINE__)
void StateMachine_Enter_NRE_CMockIgnoreArg_enteringNewState(UNITY_LINE_TYPE cmock_line);

#endif
