/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockadc.h"

static const char* CMockString_ADC_GetConversion = "ADC_GetConversion";
static const char* CMockString_ADC_GetConversionResult = "ADC_GetConversionResult";
static const char* CMockString_ADC_Initialize = "ADC_Initialize";
static const char* CMockString_ADC_IsConversionDone = "ADC_IsConversionDone";
static const char* CMockString_ADC_SelectChannel = "ADC_SelectChannel";
static const char* CMockString_ADC_StartConversion = "ADC_StartConversion";
static const char* CMockString_ADC_TemperatureAcquisitionDelay = "ADC_TemperatureAcquisitionDelay";
static const char* CMockString_channel = "channel";

typedef struct _CMOCK_ADC_Initialize_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int CallOrder;

} CMOCK_ADC_Initialize_CALL_INSTANCE;

typedef struct _CMOCK_ADC_SelectChannel_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int CallOrder;
  adc_channel_t Expected_channel;
  int IgnoreArg_channel;

} CMOCK_ADC_SelectChannel_CALL_INSTANCE;

typedef struct _CMOCK_ADC_StartConversion_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int CallOrder;

} CMOCK_ADC_StartConversion_CALL_INSTANCE;

typedef struct _CMOCK_ADC_IsConversionDone_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  _Bool ReturnVal;
  int CallOrder;

} CMOCK_ADC_IsConversionDone_CALL_INSTANCE;

typedef struct _CMOCK_ADC_GetConversionResult_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  adc_result_t ReturnVal;
  int CallOrder;

} CMOCK_ADC_GetConversionResult_CALL_INSTANCE;

typedef struct _CMOCK_ADC_GetConversion_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  adc_result_t ReturnVal;
  int CallOrder;
  adc_channel_t Expected_channel;
  int IgnoreArg_channel;

} CMOCK_ADC_GetConversion_CALL_INSTANCE;

typedef struct _CMOCK_ADC_TemperatureAcquisitionDelay_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int CallOrder;

} CMOCK_ADC_TemperatureAcquisitionDelay_CALL_INSTANCE;

static struct MockadcInstance
{
  int ADC_Initialize_IgnoreBool;
  CMOCK_ADC_Initialize_CALLBACK ADC_Initialize_CallbackFunctionPointer;
  int ADC_Initialize_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ADC_Initialize_CallInstance;
  int ADC_SelectChannel_IgnoreBool;
  CMOCK_ADC_SelectChannel_CALLBACK ADC_SelectChannel_CallbackFunctionPointer;
  int ADC_SelectChannel_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ADC_SelectChannel_CallInstance;
  int ADC_StartConversion_IgnoreBool;
  CMOCK_ADC_StartConversion_CALLBACK ADC_StartConversion_CallbackFunctionPointer;
  int ADC_StartConversion_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ADC_StartConversion_CallInstance;
  int ADC_IsConversionDone_IgnoreBool;
  _Bool ADC_IsConversionDone_FinalReturn;
  CMOCK_ADC_IsConversionDone_CALLBACK ADC_IsConversionDone_CallbackFunctionPointer;
  int ADC_IsConversionDone_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ADC_IsConversionDone_CallInstance;
  int ADC_GetConversionResult_IgnoreBool;
  adc_result_t ADC_GetConversionResult_FinalReturn;
  CMOCK_ADC_GetConversionResult_CALLBACK ADC_GetConversionResult_CallbackFunctionPointer;
  int ADC_GetConversionResult_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ADC_GetConversionResult_CallInstance;
  int ADC_GetConversion_IgnoreBool;
  adc_result_t ADC_GetConversion_FinalReturn;
  CMOCK_ADC_GetConversion_CALLBACK ADC_GetConversion_CallbackFunctionPointer;
  int ADC_GetConversion_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ADC_GetConversion_CallInstance;
  int ADC_TemperatureAcquisitionDelay_IgnoreBool;
  CMOCK_ADC_TemperatureAcquisitionDelay_CALLBACK ADC_TemperatureAcquisitionDelay_CallbackFunctionPointer;
  int ADC_TemperatureAcquisitionDelay_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE ADC_TemperatureAcquisitionDelay_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void Mockadc_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.ADC_Initialize_IgnoreBool)
    Mock.ADC_Initialize_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_ADC_Initialize);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.ADC_Initialize_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.ADC_Initialize_CallbackFunctionPointer != NULL)
    Mock.ADC_Initialize_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.ADC_SelectChannel_IgnoreBool)
    Mock.ADC_SelectChannel_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_ADC_SelectChannel);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.ADC_SelectChannel_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.ADC_SelectChannel_CallbackFunctionPointer != NULL)
    Mock.ADC_SelectChannel_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.ADC_StartConversion_IgnoreBool)
    Mock.ADC_StartConversion_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_ADC_StartConversion);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.ADC_StartConversion_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.ADC_StartConversion_CallbackFunctionPointer != NULL)
    Mock.ADC_StartConversion_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.ADC_IsConversionDone_IgnoreBool)
    Mock.ADC_IsConversionDone_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_ADC_IsConversionDone);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.ADC_IsConversionDone_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.ADC_IsConversionDone_CallbackFunctionPointer != NULL)
    Mock.ADC_IsConversionDone_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.ADC_GetConversionResult_IgnoreBool)
    Mock.ADC_GetConversionResult_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_ADC_GetConversionResult);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.ADC_GetConversionResult_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.ADC_GetConversionResult_CallbackFunctionPointer != NULL)
    Mock.ADC_GetConversionResult_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.ADC_GetConversion_IgnoreBool)
    Mock.ADC_GetConversion_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_ADC_GetConversion);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.ADC_GetConversion_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.ADC_GetConversion_CallbackFunctionPointer != NULL)
    Mock.ADC_GetConversion_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.ADC_TemperatureAcquisitionDelay_IgnoreBool)
    Mock.ADC_TemperatureAcquisitionDelay_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_ADC_TemperatureAcquisitionDelay);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.ADC_TemperatureAcquisitionDelay_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.ADC_TemperatureAcquisitionDelay_CallbackFunctionPointer != NULL)
    Mock.ADC_TemperatureAcquisitionDelay_CallInstance = CMOCK_GUTS_NONE;
}

void Mockadc_Init(void)
{
  Mockadc_Destroy();
}

void Mockadc_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.ADC_Initialize_CallbackFunctionPointer = NULL;
  Mock.ADC_Initialize_CallbackCalls = 0;
  Mock.ADC_SelectChannel_CallbackFunctionPointer = NULL;
  Mock.ADC_SelectChannel_CallbackCalls = 0;
  Mock.ADC_StartConversion_CallbackFunctionPointer = NULL;
  Mock.ADC_StartConversion_CallbackCalls = 0;
  Mock.ADC_IsConversionDone_CallbackFunctionPointer = NULL;
  Mock.ADC_IsConversionDone_CallbackCalls = 0;
  Mock.ADC_GetConversionResult_CallbackFunctionPointer = NULL;
  Mock.ADC_GetConversionResult_CallbackCalls = 0;
  Mock.ADC_GetConversion_CallbackFunctionPointer = NULL;
  Mock.ADC_GetConversion_CallbackCalls = 0;
  Mock.ADC_TemperatureAcquisitionDelay_CallbackFunctionPointer = NULL;
  Mock.ADC_TemperatureAcquisitionDelay_CallbackCalls = 0;
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void ADC_Initialize(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_ADC_Initialize);
  CMOCK_ADC_Initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_Initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ADC_Initialize_CallInstance);
  Mock.ADC_Initialize_CallInstance = CMock_Guts_MemNext(Mock.ADC_Initialize_CallInstance);
  if (Mock.ADC_Initialize_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.ADC_Initialize_CallbackFunctionPointer != NULL)
  {
    Mock.ADC_Initialize_CallbackFunctionPointer(Mock.ADC_Initialize_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  UNITY_CLR_DETAILS();
}

void ADC_Initialize_CMockIgnore(void)
{
  Mock.ADC_Initialize_IgnoreBool = (int)1;
}

void ADC_Initialize_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_Initialize_CALL_INSTANCE));
  CMOCK_ADC_Initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_Initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_Initialize_CallInstance = CMock_Guts_MemChain(Mock.ADC_Initialize_CallInstance, cmock_guts_index);
  Mock.ADC_Initialize_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void ADC_Initialize_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_Initialize_CALL_INSTANCE));
  CMOCK_ADC_Initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_Initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_Initialize_CallInstance = CMock_Guts_MemChain(Mock.ADC_Initialize_CallInstance, cmock_guts_index);
  Mock.ADC_Initialize_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  UNITY_CLR_DETAILS();
}

void ADC_Initialize_StubWithCallback(CMOCK_ADC_Initialize_CALLBACK Callback)
{
  Mock.ADC_Initialize_CallbackFunctionPointer = Callback;
}

void ADC_SelectChannel(adc_channel_t channel)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_ADC_SelectChannel);
  CMOCK_ADC_SelectChannel_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_SelectChannel_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ADC_SelectChannel_CallInstance);
  Mock.ADC_SelectChannel_CallInstance = CMock_Guts_MemNext(Mock.ADC_SelectChannel_CallInstance);
  if (Mock.ADC_SelectChannel_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.ADC_SelectChannel_CallbackFunctionPointer != NULL)
  {
    Mock.ADC_SelectChannel_CallbackFunctionPointer(channel, Mock.ADC_SelectChannel_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_channel)
  {
    UNITY_SET_DETAILS(CMockString_ADC_SelectChannel,CMockString_channel);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_channel), (void*)(&channel), sizeof(adc_channel_t), cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_ADC_SelectChannel(CMOCK_ADC_SelectChannel_CALL_INSTANCE* cmock_call_instance, adc_channel_t channel)
{
  memcpy(&cmock_call_instance->Expected_channel, &channel, sizeof(adc_channel_t));
  cmock_call_instance->IgnoreArg_channel = 0;
}

void ADC_SelectChannel_CMockIgnore(void)
{
  Mock.ADC_SelectChannel_IgnoreBool = (int)1;
}

void ADC_SelectChannel_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_SelectChannel_CALL_INSTANCE));
  CMOCK_ADC_SelectChannel_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_SelectChannel_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_SelectChannel_CallInstance = CMock_Guts_MemChain(Mock.ADC_SelectChannel_CallInstance, cmock_guts_index);
  Mock.ADC_SelectChannel_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void ADC_SelectChannel_CMockExpect(UNITY_LINE_TYPE cmock_line, adc_channel_t channel)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_SelectChannel_CALL_INSTANCE));
  CMOCK_ADC_SelectChannel_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_SelectChannel_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_SelectChannel_CallInstance = CMock_Guts_MemChain(Mock.ADC_SelectChannel_CallInstance, cmock_guts_index);
  Mock.ADC_SelectChannel_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_ADC_SelectChannel(cmock_call_instance, channel);
  UNITY_CLR_DETAILS();
}

void ADC_SelectChannel_StubWithCallback(CMOCK_ADC_SelectChannel_CALLBACK Callback)
{
  Mock.ADC_SelectChannel_CallbackFunctionPointer = Callback;
}

void ADC_SelectChannel_CMockIgnoreArg_channel(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ADC_SelectChannel_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_SelectChannel_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ADC_SelectChannel_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_channel = 1;
}

void ADC_StartConversion(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_ADC_StartConversion);
  CMOCK_ADC_StartConversion_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_StartConversion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ADC_StartConversion_CallInstance);
  Mock.ADC_StartConversion_CallInstance = CMock_Guts_MemNext(Mock.ADC_StartConversion_CallInstance);
  if (Mock.ADC_StartConversion_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.ADC_StartConversion_CallbackFunctionPointer != NULL)
  {
    Mock.ADC_StartConversion_CallbackFunctionPointer(Mock.ADC_StartConversion_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  UNITY_CLR_DETAILS();
}

void ADC_StartConversion_CMockIgnore(void)
{
  Mock.ADC_StartConversion_IgnoreBool = (int)1;
}

void ADC_StartConversion_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_StartConversion_CALL_INSTANCE));
  CMOCK_ADC_StartConversion_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_StartConversion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_StartConversion_CallInstance = CMock_Guts_MemChain(Mock.ADC_StartConversion_CallInstance, cmock_guts_index);
  Mock.ADC_StartConversion_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void ADC_StartConversion_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_StartConversion_CALL_INSTANCE));
  CMOCK_ADC_StartConversion_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_StartConversion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_StartConversion_CallInstance = CMock_Guts_MemChain(Mock.ADC_StartConversion_CallInstance, cmock_guts_index);
  Mock.ADC_StartConversion_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  UNITY_CLR_DETAILS();
}

void ADC_StartConversion_StubWithCallback(CMOCK_ADC_StartConversion_CALLBACK Callback)
{
  Mock.ADC_StartConversion_CallbackFunctionPointer = Callback;
}

_Bool ADC_IsConversionDone(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_ADC_IsConversionDone);
  CMOCK_ADC_IsConversionDone_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_IsConversionDone_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ADC_IsConversionDone_CallInstance);
  Mock.ADC_IsConversionDone_CallInstance = CMock_Guts_MemNext(Mock.ADC_IsConversionDone_CallInstance);
  if (Mock.ADC_IsConversionDone_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.ADC_IsConversionDone_FinalReturn;
    memcpy(&Mock.ADC_IsConversionDone_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(_Bool));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.ADC_IsConversionDone_CallbackFunctionPointer != NULL)
  {
    return Mock.ADC_IsConversionDone_CallbackFunctionPointer(Mock.ADC_IsConversionDone_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void ADC_IsConversionDone_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_IsConversionDone_CALL_INSTANCE));
  CMOCK_ADC_IsConversionDone_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_IsConversionDone_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_IsConversionDone_CallInstance = CMock_Guts_MemChain(Mock.ADC_IsConversionDone_CallInstance, cmock_guts_index);
  Mock.ADC_IsConversionDone_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.ADC_IsConversionDone_IgnoreBool = (int)1;
}

void ADC_IsConversionDone_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_IsConversionDone_CALL_INSTANCE));
  CMOCK_ADC_IsConversionDone_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_IsConversionDone_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_IsConversionDone_CallInstance = CMock_Guts_MemChain(Mock.ADC_IsConversionDone_CallInstance, cmock_guts_index);
  Mock.ADC_IsConversionDone_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void ADC_IsConversionDone_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_IsConversionDone_CALL_INSTANCE));
  CMOCK_ADC_IsConversionDone_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_IsConversionDone_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_IsConversionDone_CallInstance = CMock_Guts_MemChain(Mock.ADC_IsConversionDone_CallInstance, cmock_guts_index);
  Mock.ADC_IsConversionDone_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(_Bool));
  UNITY_CLR_DETAILS();
}

void ADC_IsConversionDone_StubWithCallback(CMOCK_ADC_IsConversionDone_CALLBACK Callback)
{
  Mock.ADC_IsConversionDone_CallbackFunctionPointer = Callback;
}

adc_result_t ADC_GetConversionResult(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_ADC_GetConversionResult);
  CMOCK_ADC_GetConversionResult_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_GetConversionResult_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ADC_GetConversionResult_CallInstance);
  Mock.ADC_GetConversionResult_CallInstance = CMock_Guts_MemNext(Mock.ADC_GetConversionResult_CallInstance);
  if (Mock.ADC_GetConversionResult_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.ADC_GetConversionResult_FinalReturn;
    memcpy(&Mock.ADC_GetConversionResult_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(adc_result_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.ADC_GetConversionResult_CallbackFunctionPointer != NULL)
  {
    return Mock.ADC_GetConversionResult_CallbackFunctionPointer(Mock.ADC_GetConversionResult_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void ADC_GetConversionResult_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, adc_result_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_GetConversionResult_CALL_INSTANCE));
  CMOCK_ADC_GetConversionResult_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_GetConversionResult_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_GetConversionResult_CallInstance = CMock_Guts_MemChain(Mock.ADC_GetConversionResult_CallInstance, cmock_guts_index);
  Mock.ADC_GetConversionResult_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.ADC_GetConversionResult_IgnoreBool = (int)1;
}

void ADC_GetConversionResult_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, adc_result_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_GetConversionResult_CALL_INSTANCE));
  CMOCK_ADC_GetConversionResult_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_GetConversionResult_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_GetConversionResult_CallInstance = CMock_Guts_MemChain(Mock.ADC_GetConversionResult_CallInstance, cmock_guts_index);
  Mock.ADC_GetConversionResult_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void ADC_GetConversionResult_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, adc_result_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_GetConversionResult_CALL_INSTANCE));
  CMOCK_ADC_GetConversionResult_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_GetConversionResult_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_GetConversionResult_CallInstance = CMock_Guts_MemChain(Mock.ADC_GetConversionResult_CallInstance, cmock_guts_index);
  Mock.ADC_GetConversionResult_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(adc_result_t));
  UNITY_CLR_DETAILS();
}

void ADC_GetConversionResult_StubWithCallback(CMOCK_ADC_GetConversionResult_CALLBACK Callback)
{
  Mock.ADC_GetConversionResult_CallbackFunctionPointer = Callback;
}

adc_result_t ADC_GetConversion(adc_channel_t channel)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_ADC_GetConversion);
  CMOCK_ADC_GetConversion_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_GetConversion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ADC_GetConversion_CallInstance);
  Mock.ADC_GetConversion_CallInstance = CMock_Guts_MemNext(Mock.ADC_GetConversion_CallInstance);
  if (Mock.ADC_GetConversion_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.ADC_GetConversion_FinalReturn;
    memcpy(&Mock.ADC_GetConversion_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(adc_result_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.ADC_GetConversion_CallbackFunctionPointer != NULL)
  {
    return Mock.ADC_GetConversion_CallbackFunctionPointer(channel, Mock.ADC_GetConversion_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_channel)
  {
    UNITY_SET_DETAILS(CMockString_ADC_GetConversion,CMockString_channel);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_channel), (void*)(&channel), sizeof(adc_channel_t), cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_ADC_GetConversion(CMOCK_ADC_GetConversion_CALL_INSTANCE* cmock_call_instance, adc_channel_t channel)
{
  memcpy(&cmock_call_instance->Expected_channel, &channel, sizeof(adc_channel_t));
  cmock_call_instance->IgnoreArg_channel = 0;
}

void ADC_GetConversion_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, adc_result_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_GetConversion_CALL_INSTANCE));
  CMOCK_ADC_GetConversion_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_GetConversion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_GetConversion_CallInstance = CMock_Guts_MemChain(Mock.ADC_GetConversion_CallInstance, cmock_guts_index);
  Mock.ADC_GetConversion_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.ADC_GetConversion_IgnoreBool = (int)1;
}

void ADC_GetConversion_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, adc_result_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_GetConversion_CALL_INSTANCE));
  CMOCK_ADC_GetConversion_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_GetConversion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_GetConversion_CallInstance = CMock_Guts_MemChain(Mock.ADC_GetConversion_CallInstance, cmock_guts_index);
  Mock.ADC_GetConversion_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void ADC_GetConversion_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, adc_channel_t channel, adc_result_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_GetConversion_CALL_INSTANCE));
  CMOCK_ADC_GetConversion_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_GetConversion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_GetConversion_CallInstance = CMock_Guts_MemChain(Mock.ADC_GetConversion_CallInstance, cmock_guts_index);
  Mock.ADC_GetConversion_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_ADC_GetConversion(cmock_call_instance, channel);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(adc_result_t));
  UNITY_CLR_DETAILS();
}

void ADC_GetConversion_StubWithCallback(CMOCK_ADC_GetConversion_CALLBACK Callback)
{
  Mock.ADC_GetConversion_CallbackFunctionPointer = Callback;
}

void ADC_GetConversion_CMockIgnoreArg_channel(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_ADC_GetConversion_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_GetConversion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.ADC_GetConversion_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_channel = 1;
}

void ADC_TemperatureAcquisitionDelay(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_ADC_TemperatureAcquisitionDelay);
  CMOCK_ADC_TemperatureAcquisitionDelay_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_TemperatureAcquisitionDelay_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.ADC_TemperatureAcquisitionDelay_CallInstance);
  Mock.ADC_TemperatureAcquisitionDelay_CallInstance = CMock_Guts_MemNext(Mock.ADC_TemperatureAcquisitionDelay_CallInstance);
  if (Mock.ADC_TemperatureAcquisitionDelay_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.ADC_TemperatureAcquisitionDelay_CallbackFunctionPointer != NULL)
  {
    Mock.ADC_TemperatureAcquisitionDelay_CallbackFunctionPointer(Mock.ADC_TemperatureAcquisitionDelay_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  UNITY_CLR_DETAILS();
}

void ADC_TemperatureAcquisitionDelay_CMockIgnore(void)
{
  Mock.ADC_TemperatureAcquisitionDelay_IgnoreBool = (int)1;
}

void ADC_TemperatureAcquisitionDelay_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_TemperatureAcquisitionDelay_CALL_INSTANCE));
  CMOCK_ADC_TemperatureAcquisitionDelay_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_TemperatureAcquisitionDelay_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_TemperatureAcquisitionDelay_CallInstance = CMock_Guts_MemChain(Mock.ADC_TemperatureAcquisitionDelay_CallInstance, cmock_guts_index);
  Mock.ADC_TemperatureAcquisitionDelay_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void ADC_TemperatureAcquisitionDelay_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_ADC_TemperatureAcquisitionDelay_CALL_INSTANCE));
  CMOCK_ADC_TemperatureAcquisitionDelay_CALL_INSTANCE* cmock_call_instance = (CMOCK_ADC_TemperatureAcquisitionDelay_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.ADC_TemperatureAcquisitionDelay_CallInstance = CMock_Guts_MemChain(Mock.ADC_TemperatureAcquisitionDelay_CallInstance, cmock_guts_index);
  Mock.ADC_TemperatureAcquisitionDelay_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  UNITY_CLR_DETAILS();
}

void ADC_TemperatureAcquisitionDelay_StubWithCallback(CMOCK_ADC_TemperatureAcquisitionDelay_CALLBACK Callback)
{
  Mock.ADC_TemperatureAcquisitionDelay_CallbackFunctionPointer = Callback;
}

