/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockUIInterfaces.h"

static const char* CMockString_Colour = "Colour";
static const char* CMockString_FlashTOff = "FlashTOff";
static const char* CMockString_FlashTOn = "FlashTOn";
static const char* CMockString_UI_GetPeriodCount = "UI_GetPeriodCount";
static const char* CMockString_UI_IsPushButtonPressed = "UI_IsPushButtonPressed";
static const char* CMockString_UI_SetLED = "UI_SetLED";
static const char* CMockString_UI_UpdateLEDs = "UI_UpdateLEDs";

typedef struct _CMOCK_UI_SetLED_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int CallOrder;
  LED_Colour_t Expected_Colour;
  uint32_t Expected_FlashTOn;
  uint32_t Expected_FlashTOff;
  int IgnoreArg_Colour;
  int IgnoreArg_FlashTOn;
  int IgnoreArg_FlashTOff;

} CMOCK_UI_SetLED_CALL_INSTANCE;

typedef struct _CMOCK_UI_UpdateLEDs_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  bool_t ReturnVal;
  int CallOrder;

} CMOCK_UI_UpdateLEDs_CALL_INSTANCE;

typedef struct _CMOCK_UI_IsPushButtonPressed_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  bool_t ReturnVal;
  int CallOrder;

} CMOCK_UI_IsPushButtonPressed_CALL_INSTANCE;

typedef struct _CMOCK_UI_GetPeriodCount_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t ReturnVal;
  int CallOrder;
  LED_Colour_t Expected_Colour;
  int IgnoreArg_Colour;

} CMOCK_UI_GetPeriodCount_CALL_INSTANCE;

static struct MockUIInterfacesInstance
{
  int UI_SetLED_IgnoreBool;
  CMOCK_UI_SetLED_CALLBACK UI_SetLED_CallbackFunctionPointer;
  int UI_SetLED_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE UI_SetLED_CallInstance;
  int UI_UpdateLEDs_IgnoreBool;
  bool_t UI_UpdateLEDs_FinalReturn;
  CMOCK_UI_UpdateLEDs_CALLBACK UI_UpdateLEDs_CallbackFunctionPointer;
  int UI_UpdateLEDs_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE UI_UpdateLEDs_CallInstance;
  int UI_IsPushButtonPressed_IgnoreBool;
  bool_t UI_IsPushButtonPressed_FinalReturn;
  CMOCK_UI_IsPushButtonPressed_CALLBACK UI_IsPushButtonPressed_CallbackFunctionPointer;
  int UI_IsPushButtonPressed_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE UI_IsPushButtonPressed_CallInstance;
  int UI_GetPeriodCount_IgnoreBool;
  uint32_t UI_GetPeriodCount_FinalReturn;
  CMOCK_UI_GetPeriodCount_CALLBACK UI_GetPeriodCount_CallbackFunctionPointer;
  int UI_GetPeriodCount_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE UI_GetPeriodCount_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void MockUIInterfaces_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.UI_SetLED_IgnoreBool)
    Mock.UI_SetLED_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_UI_SetLED);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.UI_SetLED_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.UI_SetLED_CallbackFunctionPointer != NULL)
    Mock.UI_SetLED_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.UI_UpdateLEDs_IgnoreBool)
    Mock.UI_UpdateLEDs_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_UI_UpdateLEDs);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.UI_UpdateLEDs_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.UI_UpdateLEDs_CallbackFunctionPointer != NULL)
    Mock.UI_UpdateLEDs_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.UI_IsPushButtonPressed_IgnoreBool)
    Mock.UI_IsPushButtonPressed_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_UI_IsPushButtonPressed);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.UI_IsPushButtonPressed_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.UI_IsPushButtonPressed_CallbackFunctionPointer != NULL)
    Mock.UI_IsPushButtonPressed_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.UI_GetPeriodCount_IgnoreBool)
    Mock.UI_GetPeriodCount_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_UI_GetPeriodCount);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.UI_GetPeriodCount_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.UI_GetPeriodCount_CallbackFunctionPointer != NULL)
    Mock.UI_GetPeriodCount_CallInstance = CMOCK_GUTS_NONE;
}

void MockUIInterfaces_Init(void)
{
  MockUIInterfaces_Destroy();
}

void MockUIInterfaces_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.UI_SetLED_CallbackFunctionPointer = NULL;
  Mock.UI_SetLED_CallbackCalls = 0;
  Mock.UI_UpdateLEDs_CallbackFunctionPointer = NULL;
  Mock.UI_UpdateLEDs_CallbackCalls = 0;
  Mock.UI_IsPushButtonPressed_CallbackFunctionPointer = NULL;
  Mock.UI_IsPushButtonPressed_CallbackCalls = 0;
  Mock.UI_GetPeriodCount_CallbackFunctionPointer = NULL;
  Mock.UI_GetPeriodCount_CallbackCalls = 0;
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void UI_SetLED(LED_Colour_t Colour, uint32_t FlashTOn, uint32_t FlashTOff)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_UI_SetLED);
  CMOCK_UI_SetLED_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_SetLED_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.UI_SetLED_CallInstance);
  Mock.UI_SetLED_CallInstance = CMock_Guts_MemNext(Mock.UI_SetLED_CallInstance);
  if (Mock.UI_SetLED_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.UI_SetLED_CallbackFunctionPointer != NULL)
  {
    Mock.UI_SetLED_CallbackFunctionPointer(Colour, FlashTOn, FlashTOff, Mock.UI_SetLED_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_Colour)
  {
    UNITY_SET_DETAILS(CMockString_UI_SetLED,CMockString_Colour);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_Colour), (void*)(&Colour), sizeof(LED_Colour_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_FlashTOn)
  {
    UNITY_SET_DETAILS(CMockString_UI_SetLED,CMockString_FlashTOn);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_FlashTOn, FlashTOn, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_FlashTOff)
  {
    UNITY_SET_DETAILS(CMockString_UI_SetLED,CMockString_FlashTOff);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_FlashTOff, FlashTOff, cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_UI_SetLED(CMOCK_UI_SetLED_CALL_INSTANCE* cmock_call_instance, LED_Colour_t Colour, uint32_t FlashTOn, uint32_t FlashTOff)
{
  memcpy(&cmock_call_instance->Expected_Colour, &Colour, sizeof(LED_Colour_t));
  cmock_call_instance->IgnoreArg_Colour = 0;
  cmock_call_instance->Expected_FlashTOn = FlashTOn;
  cmock_call_instance->IgnoreArg_FlashTOn = 0;
  cmock_call_instance->Expected_FlashTOff = FlashTOff;
  cmock_call_instance->IgnoreArg_FlashTOff = 0;
}

void UI_SetLED_CMockIgnore(void)
{
  Mock.UI_SetLED_IgnoreBool = (int)1;
}

void UI_SetLED_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UI_SetLED_CALL_INSTANCE));
  CMOCK_UI_SetLED_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_SetLED_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UI_SetLED_CallInstance = CMock_Guts_MemChain(Mock.UI_SetLED_CallInstance, cmock_guts_index);
  Mock.UI_SetLED_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void UI_SetLED_CMockExpect(UNITY_LINE_TYPE cmock_line, LED_Colour_t Colour, uint32_t FlashTOn, uint32_t FlashTOff)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UI_SetLED_CALL_INSTANCE));
  CMOCK_UI_SetLED_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_SetLED_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UI_SetLED_CallInstance = CMock_Guts_MemChain(Mock.UI_SetLED_CallInstance, cmock_guts_index);
  Mock.UI_SetLED_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_UI_SetLED(cmock_call_instance, Colour, FlashTOn, FlashTOff);
  UNITY_CLR_DETAILS();
}

void UI_SetLED_StubWithCallback(CMOCK_UI_SetLED_CALLBACK Callback)
{
  Mock.UI_SetLED_CallbackFunctionPointer = Callback;
}

void UI_SetLED_CMockIgnoreArg_Colour(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_UI_SetLED_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_SetLED_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.UI_SetLED_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_Colour = 1;
}

void UI_SetLED_CMockIgnoreArg_FlashTOn(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_UI_SetLED_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_SetLED_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.UI_SetLED_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_FlashTOn = 1;
}

void UI_SetLED_CMockIgnoreArg_FlashTOff(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_UI_SetLED_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_SetLED_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.UI_SetLED_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_FlashTOff = 1;
}

bool_t UI_UpdateLEDs(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_UI_UpdateLEDs);
  CMOCK_UI_UpdateLEDs_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_UpdateLEDs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.UI_UpdateLEDs_CallInstance);
  Mock.UI_UpdateLEDs_CallInstance = CMock_Guts_MemNext(Mock.UI_UpdateLEDs_CallInstance);
  if (Mock.UI_UpdateLEDs_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.UI_UpdateLEDs_FinalReturn;
    Mock.UI_UpdateLEDs_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.UI_UpdateLEDs_CallbackFunctionPointer != NULL)
  {
    return Mock.UI_UpdateLEDs_CallbackFunctionPointer(Mock.UI_UpdateLEDs_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void UI_UpdateLEDs_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UI_UpdateLEDs_CALL_INSTANCE));
  CMOCK_UI_UpdateLEDs_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_UpdateLEDs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UI_UpdateLEDs_CallInstance = CMock_Guts_MemChain(Mock.UI_UpdateLEDs_CallInstance, cmock_guts_index);
  Mock.UI_UpdateLEDs_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.UI_UpdateLEDs_IgnoreBool = (int)1;
}

void UI_UpdateLEDs_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UI_UpdateLEDs_CALL_INSTANCE));
  CMOCK_UI_UpdateLEDs_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_UpdateLEDs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UI_UpdateLEDs_CallInstance = CMock_Guts_MemChain(Mock.UI_UpdateLEDs_CallInstance, cmock_guts_index);
  Mock.UI_UpdateLEDs_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void UI_UpdateLEDs_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UI_UpdateLEDs_CALL_INSTANCE));
  CMOCK_UI_UpdateLEDs_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_UpdateLEDs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UI_UpdateLEDs_CallInstance = CMock_Guts_MemChain(Mock.UI_UpdateLEDs_CallInstance, cmock_guts_index);
  Mock.UI_UpdateLEDs_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void UI_UpdateLEDs_StubWithCallback(CMOCK_UI_UpdateLEDs_CALLBACK Callback)
{
  Mock.UI_UpdateLEDs_CallbackFunctionPointer = Callback;
}

bool_t UI_IsPushButtonPressed(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_UI_IsPushButtonPressed);
  CMOCK_UI_IsPushButtonPressed_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_IsPushButtonPressed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.UI_IsPushButtonPressed_CallInstance);
  Mock.UI_IsPushButtonPressed_CallInstance = CMock_Guts_MemNext(Mock.UI_IsPushButtonPressed_CallInstance);
  if (Mock.UI_IsPushButtonPressed_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.UI_IsPushButtonPressed_FinalReturn;
    Mock.UI_IsPushButtonPressed_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.UI_IsPushButtonPressed_CallbackFunctionPointer != NULL)
  {
    return Mock.UI_IsPushButtonPressed_CallbackFunctionPointer(Mock.UI_IsPushButtonPressed_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void UI_IsPushButtonPressed_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UI_IsPushButtonPressed_CALL_INSTANCE));
  CMOCK_UI_IsPushButtonPressed_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_IsPushButtonPressed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UI_IsPushButtonPressed_CallInstance = CMock_Guts_MemChain(Mock.UI_IsPushButtonPressed_CallInstance, cmock_guts_index);
  Mock.UI_IsPushButtonPressed_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.UI_IsPushButtonPressed_IgnoreBool = (int)1;
}

void UI_IsPushButtonPressed_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UI_IsPushButtonPressed_CALL_INSTANCE));
  CMOCK_UI_IsPushButtonPressed_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_IsPushButtonPressed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UI_IsPushButtonPressed_CallInstance = CMock_Guts_MemChain(Mock.UI_IsPushButtonPressed_CallInstance, cmock_guts_index);
  Mock.UI_IsPushButtonPressed_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void UI_IsPushButtonPressed_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UI_IsPushButtonPressed_CALL_INSTANCE));
  CMOCK_UI_IsPushButtonPressed_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_IsPushButtonPressed_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UI_IsPushButtonPressed_CallInstance = CMock_Guts_MemChain(Mock.UI_IsPushButtonPressed_CallInstance, cmock_guts_index);
  Mock.UI_IsPushButtonPressed_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void UI_IsPushButtonPressed_StubWithCallback(CMOCK_UI_IsPushButtonPressed_CALLBACK Callback)
{
  Mock.UI_IsPushButtonPressed_CallbackFunctionPointer = Callback;
}

uint32_t UI_GetPeriodCount(LED_Colour_t Colour)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_UI_GetPeriodCount);
  CMOCK_UI_GetPeriodCount_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_GetPeriodCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.UI_GetPeriodCount_CallInstance);
  Mock.UI_GetPeriodCount_CallInstance = CMock_Guts_MemNext(Mock.UI_GetPeriodCount_CallInstance);
  if (Mock.UI_GetPeriodCount_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.UI_GetPeriodCount_FinalReturn;
    Mock.UI_GetPeriodCount_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.UI_GetPeriodCount_CallbackFunctionPointer != NULL)
  {
    return Mock.UI_GetPeriodCount_CallbackFunctionPointer(Colour, Mock.UI_GetPeriodCount_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_Colour)
  {
    UNITY_SET_DETAILS(CMockString_UI_GetPeriodCount,CMockString_Colour);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_Colour), (void*)(&Colour), sizeof(LED_Colour_t), cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_UI_GetPeriodCount(CMOCK_UI_GetPeriodCount_CALL_INSTANCE* cmock_call_instance, LED_Colour_t Colour)
{
  memcpy(&cmock_call_instance->Expected_Colour, &Colour, sizeof(LED_Colour_t));
  cmock_call_instance->IgnoreArg_Colour = 0;
}

void UI_GetPeriodCount_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UI_GetPeriodCount_CALL_INSTANCE));
  CMOCK_UI_GetPeriodCount_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_GetPeriodCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UI_GetPeriodCount_CallInstance = CMock_Guts_MemChain(Mock.UI_GetPeriodCount_CallInstance, cmock_guts_index);
  Mock.UI_GetPeriodCount_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.UI_GetPeriodCount_IgnoreBool = (int)1;
}

void UI_GetPeriodCount_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UI_GetPeriodCount_CALL_INSTANCE));
  CMOCK_UI_GetPeriodCount_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_GetPeriodCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UI_GetPeriodCount_CallInstance = CMock_Guts_MemChain(Mock.UI_GetPeriodCount_CallInstance, cmock_guts_index);
  Mock.UI_GetPeriodCount_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void UI_GetPeriodCount_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, LED_Colour_t Colour, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UI_GetPeriodCount_CALL_INSTANCE));
  CMOCK_UI_GetPeriodCount_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_GetPeriodCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.UI_GetPeriodCount_CallInstance = CMock_Guts_MemChain(Mock.UI_GetPeriodCount_CallInstance, cmock_guts_index);
  Mock.UI_GetPeriodCount_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_UI_GetPeriodCount(cmock_call_instance, Colour);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void UI_GetPeriodCount_StubWithCallback(CMOCK_UI_GetPeriodCount_CALLBACK Callback)
{
  Mock.UI_GetPeriodCount_CallbackFunctionPointer = Callback;
}

void UI_GetPeriodCount_CMockIgnoreArg_Colour(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_UI_GetPeriodCount_CALL_INSTANCE* cmock_call_instance = (CMOCK_UI_GetPeriodCount_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.UI_GetPeriodCount_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_Colour = 1;
}

