/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSTATEMACHINEPUMPDOWN_H
#define _MOCKSTATEMACHINEPUMPDOWN_H

#include "StateMachinePumpDown.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockStateMachinePumpDown_Init(void);
void MockStateMachinePumpDown_Destroy(void);
void MockStateMachinePumpDown_Verify(void);




#define PumpDown_IgnoreAndReturn(cmock_retval) PumpDown_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void PumpDown_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
#define PumpDown_ExpectAnyArgsAndReturn(cmock_retval) PumpDown_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void PumpDown_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
#define PumpDown_ExpectAndReturn(cmock_arg1, cmock_arg2, cmock_retval) PumpDown_CMockExpectAndReturn(__LINE__, cmock_arg1, cmock_arg2, cmock_retval)
void PumpDown_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool_t cmock_arg1, State_t* cmock_arg2, ErrorCode_t cmock_to_return);
typedef ErrorCode_t (* CMOCK_PumpDown_CALLBACK)(bool_t cmock_arg1, State_t* cmock_arg2, int cmock_num_calls);
void PumpDown_StubWithCallback(CMOCK_PumpDown_CALLBACK Callback);
#define PumpDown_ExpectWithArrayAndReturn(cmock_arg1, cmock_arg2, cmock_arg2_Depth, cmock_retval) PumpDown_CMockExpectWithArrayAndReturn(__LINE__, cmock_arg1, cmock_arg2, cmock_arg2_Depth, cmock_retval)
void PumpDown_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, bool_t cmock_arg1, State_t* cmock_arg2, int cmock_arg2_Depth, ErrorCode_t cmock_to_return);
#define PumpDown_ReturnThruPtr_cmock_arg2(cmock_arg2) PumpDown_CMockReturnMemThruPtr_cmock_arg2(__LINE__, cmock_arg2, sizeof(*cmock_arg2))
#define PumpDown_ReturnArrayThruPtr_cmock_arg2(cmock_arg2, cmock_len) PumpDown_CMockReturnMemThruPtr_cmock_arg2(__LINE__, cmock_arg2, (int)(cmock_len * (int)sizeof(*cmock_arg2)))
#define PumpDown_ReturnMemThruPtr_cmock_arg2(cmock_arg2, cmock_size) PumpDown_CMockReturnMemThruPtr_cmock_arg2(__LINE__, cmock_arg2, cmock_size)
void PumpDown_CMockReturnMemThruPtr_cmock_arg2(UNITY_LINE_TYPE cmock_line, State_t* cmock_arg2, int cmock_size);
#define PumpDown_IgnoreArg_cmock_arg1() PumpDown_CMockIgnoreArg_cmock_arg1(__LINE__)
void PumpDown_CMockIgnoreArg_cmock_arg1(UNITY_LINE_TYPE cmock_line);
#define PumpDown_IgnoreArg_cmock_arg2() PumpDown_CMockIgnoreArg_cmock_arg2(__LINE__)
void PumpDown_CMockIgnoreArg_cmock_arg2(UNITY_LINE_TYPE cmock_line);
#define PumpDown_Init_IgnoreAndReturn(cmock_retval) PumpDown_Init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void PumpDown_Init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
#define PumpDown_Init_ExpectAnyArgsAndReturn(cmock_retval) PumpDown_Init_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void PumpDown_Init_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
#define PumpDown_Init_ExpectAndReturn(cmock_retval) PumpDown_Init_CMockExpectAndReturn(__LINE__, cmock_retval)
void PumpDown_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
typedef ErrorCode_t (* CMOCK_PumpDown_Init_CALLBACK)(int cmock_num_calls);
void PumpDown_Init_StubWithCallback(CMOCK_PumpDown_Init_CALLBACK Callback);

#endif
