/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  CMock_Init(); \
  UNITY_CLR_DETAILS(); \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
    CMock_Verify(); \
  } \
  CMock_Destroy(); \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include <setjmp.h>
#include <stdio.h>
#include "MockTimer.h"
#include "MockPump.h"
#include "MockPushButton.h"
#include "MockPressure_Part1.h"
#include "MockPressure_Part3.h"
#include "MockPowerControl.h"
#include "MockDutyCycle.h"
#include "MockDeviceStatus.h"
#include "MockStateMachineCommon.h"
#include "MockPerformanceLogger.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_InitialiseInternalVariablesAndReturnOk(void);
extern void test_InvalidParameterForDeliveryTherapyStateFunctionThatReurnsAnError(void);
extern void test_TherapyDeliveryStateReturnsInvalidInputParameter(void);
extern void test_TherapyDeliveryOnEntryFromDifferntState(void);
extern void test_TherapyDeliveryDetectLeakAndGoIntoFault(void);
extern void test_TherapyDeliveryStopAndEnterNREWhenReliablePreassureAndTemperatureReadingsCantBeObtainedFromSensorsExtInitalise(void);
extern void test_TherapyDeliveryStopAndEnterNREWhenReliablePreassureAndTemperatureReadingsCantBeObtainedFromSensorsExtStart(void);
extern void test_TherapyDeliveryStopAndEnterNREWhenReliablePreassureAndTemperatureReadingsCantBeObtainedFromSensorsExtNotReady(void);
extern void test_TherapyDeliveryStopAndEnterNREWhenReliablePreassureAndTemperatureReadingsCantBeObtainedFromSensorsExtReadExtReadFail(void);
extern void test_TherapyDeliveryStopAndEnterNREWhenReliablePreassureAndTemperatureReadingsCantBeObtainedFromSensorsIntInitalise(void);
extern void test_TherapyDeliveryStopAndEnterNREWhenReliablePreassureAndTemperatureReadingsCantBeObtainedFromSensorsIntStart(void);
extern void test_TherapyDeliveryStopAndEnterNREWhenReliablePreassureAndTemperatureReadingsCantBeObtainedFromSensorsIntNotReady(void);
extern void test_TherapyDeliveryStopAndEnterNREWhenReliablePreassureAndTemperatureReadingsCantBeObtainedFromSensorsIntReadIntReadFail(void);
extern void test_TherapyDeliveryDetectExternalTemperatureThreshholdAndEnterNRE(void);
extern void test_TherapyDeliveryDetectInternalTemperatureThreshholdAndEnterNRE(void);
extern void test_TherapyDeliveryDetectsShortButtonPressAndEnablesTheAlertsForTheDeviceStatusCheck(void);
extern void test_TherapyDeliveryDetectLongButtonPressAndEventuallyGoesInShutdown(void);
extern void test_TherapyDeliveryVacuumAtTargetValueDoNotPumpOn(void);
extern void test_TherapyDeliveryVacuumBelowTargetValueThereforeDoPumpOn(void);
extern void test_TherapyDeliveryUpdateTargetVacuumPeriodicallyToSaveBattery(void);
extern void test_TherapyDeliveryFailToActivatePumpAndGoToEitherFaultOrNonRecoverableError(void);
extern void test_TherapyDeliveryDetectHighExternalPressureAndGoIntoFault(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  MockTimer_Init();
  MockPump_Init();
  MockPushButton_Init();
  MockPressure_Part1_Init();
  MockPressure_Part3_Init();
  MockPowerControl_Init();
  MockDutyCycle_Init();
  MockDeviceStatus_Init();
  MockStateMachineCommon_Init();
  MockPerformanceLogger_Init();
}
static void CMock_Verify(void)
{
  MockTimer_Verify();
  MockPump_Verify();
  MockPushButton_Verify();
  MockPressure_Part1_Verify();
  MockPressure_Part3_Verify();
  MockPowerControl_Verify();
  MockDutyCycle_Verify();
  MockDeviceStatus_Verify();
  MockStateMachineCommon_Verify();
  MockPerformanceLogger_Verify();
}
static void CMock_Destroy(void)
{
  MockTimer_Destroy();
  MockPump_Destroy();
  MockPushButton_Destroy();
  MockPressure_Part1_Destroy();
  MockPressure_Part3_Destroy();
  MockPowerControl_Destroy();
  MockDutyCycle_Destroy();
  MockDeviceStatus_Destroy();
  MockStateMachineCommon_Destroy();
  MockPerformanceLogger_Destroy();
}

/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  CMock_Verify();
  CMock_Destroy();
  tearDown();
  CMock_Init();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_StateMachineTherapyDelivery.c");
  RUN_TEST(test_InitialiseInternalVariablesAndReturnOk, 146);
  RUN_TEST(test_InvalidParameterForDeliveryTherapyStateFunctionThatReurnsAnError, 155);
  RUN_TEST(test_TherapyDeliveryStateReturnsInvalidInputParameter, 162);
  RUN_TEST(test_TherapyDeliveryOnEntryFromDifferntState, 176);
  RUN_TEST(test_TherapyDeliveryDetectLeakAndGoIntoFault, 213);
  RUN_TEST(test_TherapyDeliveryStopAndEnterNREWhenReliablePreassureAndTemperatureReadingsCantBeObtainedFromSensorsExtInitalise, 234);
  RUN_TEST(test_TherapyDeliveryStopAndEnterNREWhenReliablePreassureAndTemperatureReadingsCantBeObtainedFromSensorsExtStart, 256);
  RUN_TEST(test_TherapyDeliveryStopAndEnterNREWhenReliablePreassureAndTemperatureReadingsCantBeObtainedFromSensorsExtNotReady, 279);
  RUN_TEST(test_TherapyDeliveryStopAndEnterNREWhenReliablePreassureAndTemperatureReadingsCantBeObtainedFromSensorsExtReadExtReadFail, 302);
  RUN_TEST(test_TherapyDeliveryStopAndEnterNREWhenReliablePreassureAndTemperatureReadingsCantBeObtainedFromSensorsIntInitalise, 325);
  RUN_TEST(test_TherapyDeliveryStopAndEnterNREWhenReliablePreassureAndTemperatureReadingsCantBeObtainedFromSensorsIntStart, 347);
  RUN_TEST(test_TherapyDeliveryStopAndEnterNREWhenReliablePreassureAndTemperatureReadingsCantBeObtainedFromSensorsIntNotReady, 370);
  RUN_TEST(test_TherapyDeliveryStopAndEnterNREWhenReliablePreassureAndTemperatureReadingsCantBeObtainedFromSensorsIntReadIntReadFail, 393);
  RUN_TEST(test_TherapyDeliveryDetectExternalTemperatureThreshholdAndEnterNRE, 416);
  RUN_TEST(test_TherapyDeliveryDetectInternalTemperatureThreshholdAndEnterNRE, 440);
  RUN_TEST(test_TherapyDeliveryDetectsShortButtonPressAndEnablesTheAlertsForTheDeviceStatusCheck, 468);
  RUN_TEST(test_TherapyDeliveryDetectLongButtonPressAndEventuallyGoesInShutdown, 510);
  RUN_TEST(test_TherapyDeliveryVacuumAtTargetValueDoNotPumpOn, 539);
  RUN_TEST(test_TherapyDeliveryVacuumBelowTargetValueThereforeDoPumpOn, 574);
  RUN_TEST(test_TherapyDeliveryUpdateTargetVacuumPeriodicallyToSaveBattery, 621);
  RUN_TEST(test_TherapyDeliveryFailToActivatePumpAndGoToEitherFaultOrNonRecoverableError, 654);
  RUN_TEST(test_TherapyDeliveryDetectHighExternalPressureAndGoIntoFault, 721);

  CMock_Guts_MemFreeFinal();
  return (UnityEnd());
}
