/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockTransmit.h"

static const char* CMockString_TX_Init = "TX_Init";
static const char* CMockString_TX_Write = "TX_Write";
static const char* CMockString_data = "data";
static const char* CMockString_numBytes = "numBytes";

typedef struct _CMOCK_TX_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int CallOrder;

} CMOCK_TX_Init_CALL_INSTANCE;

typedef struct _CMOCK_TX_Write_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  ErrorCode_t ReturnVal;
  int CallOrder;
  uint8_t* Expected_data;
  uint8_t Expected_numBytes;
  int Expected_data_Depth;
  int IgnoreArg_data;
  int IgnoreArg_numBytes;

} CMOCK_TX_Write_CALL_INSTANCE;

static struct MockTransmitInstance
{
  int TX_Init_IgnoreBool;
  CMOCK_TX_Init_CALLBACK TX_Init_CallbackFunctionPointer;
  int TX_Init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE TX_Init_CallInstance;
  int TX_Write_IgnoreBool;
  ErrorCode_t TX_Write_FinalReturn;
  CMOCK_TX_Write_CALLBACK TX_Write_CallbackFunctionPointer;
  int TX_Write_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE TX_Write_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void MockTransmit_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.TX_Init_IgnoreBool)
    Mock.TX_Init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_TX_Init);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.TX_Init_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.TX_Init_CallbackFunctionPointer != NULL)
    Mock.TX_Init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.TX_Write_IgnoreBool)
    Mock.TX_Write_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_TX_Write);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.TX_Write_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.TX_Write_CallbackFunctionPointer != NULL)
    Mock.TX_Write_CallInstance = CMOCK_GUTS_NONE;
}

void MockTransmit_Init(void)
{
  MockTransmit_Destroy();
}

void MockTransmit_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.TX_Init_CallbackFunctionPointer = NULL;
  Mock.TX_Init_CallbackCalls = 0;
  Mock.TX_Write_CallbackFunctionPointer = NULL;
  Mock.TX_Write_CallbackCalls = 0;
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void TX_Init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_TX_Init);
  CMOCK_TX_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_TX_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TX_Init_CallInstance);
  Mock.TX_Init_CallInstance = CMock_Guts_MemNext(Mock.TX_Init_CallInstance);
  if (Mock.TX_Init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.TX_Init_CallbackFunctionPointer != NULL)
  {
    Mock.TX_Init_CallbackFunctionPointer(Mock.TX_Init_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  UNITY_CLR_DETAILS();
}

void TX_Init_CMockIgnore(void)
{
  Mock.TX_Init_IgnoreBool = (int)1;
}

void TX_Init_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TX_Init_CALL_INSTANCE));
  CMOCK_TX_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_TX_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TX_Init_CallInstance = CMock_Guts_MemChain(Mock.TX_Init_CallInstance, cmock_guts_index);
  Mock.TX_Init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void TX_Init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TX_Init_CALL_INSTANCE));
  CMOCK_TX_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_TX_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TX_Init_CallInstance = CMock_Guts_MemChain(Mock.TX_Init_CallInstance, cmock_guts_index);
  Mock.TX_Init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  UNITY_CLR_DETAILS();
}

void TX_Init_StubWithCallback(CMOCK_TX_Init_CALLBACK Callback)
{
  Mock.TX_Init_CallbackFunctionPointer = Callback;
}

ErrorCode_t TX_Write(const uint8_t* data, uint8_t numBytes)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_TX_Write);
  CMOCK_TX_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_TX_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TX_Write_CallInstance);
  Mock.TX_Write_CallInstance = CMock_Guts_MemNext(Mock.TX_Write_CallInstance);
  if (Mock.TX_Write_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.TX_Write_FinalReturn;
    memcpy(&Mock.TX_Write_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(ErrorCode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.TX_Write_CallbackFunctionPointer != NULL)
  {
    return Mock.TX_Write_CallbackFunctionPointer(data, numBytes, Mock.TX_Write_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_data)
  {
    UNITY_SET_DETAILS(CMockString_TX_Write,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, cmock_call_instance->Expected_data_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_numBytes)
  {
    UNITY_SET_DETAILS(CMockString_TX_Write,CMockString_numBytes);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_numBytes, numBytes, cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_TX_Write(CMOCK_TX_Write_CALL_INSTANCE* cmock_call_instance, const uint8_t* data, int data_Depth, uint8_t numBytes)
{
  cmock_call_instance->Expected_data = (uint8_t*)data;
  cmock_call_instance->Expected_data_Depth = data_Depth;
  cmock_call_instance->IgnoreArg_data = 0;
  cmock_call_instance->Expected_numBytes = numBytes;
  cmock_call_instance->IgnoreArg_numBytes = 0;
}

void TX_Write_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TX_Write_CALL_INSTANCE));
  CMOCK_TX_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_TX_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TX_Write_CallInstance = CMock_Guts_MemChain(Mock.TX_Write_CallInstance, cmock_guts_index);
  Mock.TX_Write_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.TX_Write_IgnoreBool = (int)1;
}

void TX_Write_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TX_Write_CALL_INSTANCE));
  CMOCK_TX_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_TX_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TX_Write_CallInstance = CMock_Guts_MemChain(Mock.TX_Write_CallInstance, cmock_guts_index);
  Mock.TX_Write_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void TX_Write_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t* data, uint8_t numBytes, ErrorCode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TX_Write_CALL_INSTANCE));
  CMOCK_TX_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_TX_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TX_Write_CallInstance = CMock_Guts_MemChain(Mock.TX_Write_CallInstance, cmock_guts_index);
  Mock.TX_Write_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_TX_Write(cmock_call_instance, data, 1, numBytes);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(ErrorCode_t));
  UNITY_CLR_DETAILS();
}

void TX_Write_StubWithCallback(CMOCK_TX_Write_CALLBACK Callback)
{
  Mock.TX_Write_CallbackFunctionPointer = Callback;
}

void TX_Write_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, const uint8_t* data, int data_Depth, uint8_t numBytes, ErrorCode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TX_Write_CALL_INSTANCE));
  CMOCK_TX_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_TX_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TX_Write_CallInstance = CMock_Guts_MemChain(Mock.TX_Write_CallInstance, cmock_guts_index);
  Mock.TX_Write_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_TX_Write(cmock_call_instance, data, data_Depth, numBytes);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void TX_Write_CMockIgnoreArg_data(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_TX_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_TX_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.TX_Write_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data = 1;
}

void TX_Write_CMockIgnoreArg_numBytes(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_TX_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_TX_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.TX_Write_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_numBytes = 1;
}

