/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockI2CEEPROM.h"

static const char* CMockString_I2E_Init = "I2E_Init";
static const char* CMockString_I2E_Read = "I2E_Read";
static const char* CMockString_I2E_Write = "I2E_Write";
static const char* CMockString_address = "address";
static const char* CMockString_data = "data";
static const char* CMockString_numBytes = "numBytes";

typedef struct _CMOCK_I2E_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int CallOrder;

} CMOCK_I2E_Init_CALL_INSTANCE;

typedef struct _CMOCK_I2E_Read_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  ErrorCode_t ReturnVal;
  int CallOrder;
  uint32_t Expected_address;
  uint8_t* Expected_data;
  uint8_t Expected_numBytes;
  int Expected_data_Depth;
  int ReturnThruPtr_data_Used;
  uint8_t* ReturnThruPtr_data_Val;
  int ReturnThruPtr_data_Size;
  int IgnoreArg_address;
  int IgnoreArg_data;
  int IgnoreArg_numBytes;

} CMOCK_I2E_Read_CALL_INSTANCE;

typedef struct _CMOCK_I2E_Write_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  ErrorCode_t ReturnVal;
  int CallOrder;
  uint32_t Expected_address;
  uint8_t* Expected_data;
  uint8_t Expected_numBytes;
  int Expected_data_Depth;
  int IgnoreArg_address;
  int IgnoreArg_data;
  int IgnoreArg_numBytes;

} CMOCK_I2E_Write_CALL_INSTANCE;

static struct MockI2CEEPROMInstance
{
  int I2E_Init_IgnoreBool;
  CMOCK_I2E_Init_CALLBACK I2E_Init_CallbackFunctionPointer;
  int I2E_Init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE I2E_Init_CallInstance;
  int I2E_Read_IgnoreBool;
  ErrorCode_t I2E_Read_FinalReturn;
  CMOCK_I2E_Read_CALLBACK I2E_Read_CallbackFunctionPointer;
  int I2E_Read_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE I2E_Read_CallInstance;
  int I2E_Write_IgnoreBool;
  ErrorCode_t I2E_Write_FinalReturn;
  CMOCK_I2E_Write_CALLBACK I2E_Write_CallbackFunctionPointer;
  int I2E_Write_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE I2E_Write_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void MockI2CEEPROM_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.I2E_Init_IgnoreBool)
    Mock.I2E_Init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_I2E_Init);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.I2E_Init_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.I2E_Init_CallbackFunctionPointer != NULL)
    Mock.I2E_Init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.I2E_Read_IgnoreBool)
    Mock.I2E_Read_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_I2E_Read);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.I2E_Read_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.I2E_Read_CallbackFunctionPointer != NULL)
    Mock.I2E_Read_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.I2E_Write_IgnoreBool)
    Mock.I2E_Write_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_I2E_Write);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.I2E_Write_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.I2E_Write_CallbackFunctionPointer != NULL)
    Mock.I2E_Write_CallInstance = CMOCK_GUTS_NONE;
}

void MockI2CEEPROM_Init(void)
{
  MockI2CEEPROM_Destroy();
}

void MockI2CEEPROM_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.I2E_Init_CallbackFunctionPointer = NULL;
  Mock.I2E_Init_CallbackCalls = 0;
  Mock.I2E_Read_CallbackFunctionPointer = NULL;
  Mock.I2E_Read_CallbackCalls = 0;
  Mock.I2E_Write_CallbackFunctionPointer = NULL;
  Mock.I2E_Write_CallbackCalls = 0;
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void I2E_Init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_I2E_Init);
  CMOCK_I2E_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2E_Init_CallInstance);
  Mock.I2E_Init_CallInstance = CMock_Guts_MemNext(Mock.I2E_Init_CallInstance);
  if (Mock.I2E_Init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.I2E_Init_CallbackFunctionPointer != NULL)
  {
    Mock.I2E_Init_CallbackFunctionPointer(Mock.I2E_Init_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  UNITY_CLR_DETAILS();
}

void I2E_Init_CMockIgnore(void)
{
  Mock.I2E_Init_IgnoreBool = (int)1;
}

void I2E_Init_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2E_Init_CALL_INSTANCE));
  CMOCK_I2E_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2E_Init_CallInstance = CMock_Guts_MemChain(Mock.I2E_Init_CallInstance, cmock_guts_index);
  Mock.I2E_Init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void I2E_Init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2E_Init_CALL_INSTANCE));
  CMOCK_I2E_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2E_Init_CallInstance = CMock_Guts_MemChain(Mock.I2E_Init_CallInstance, cmock_guts_index);
  Mock.I2E_Init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  UNITY_CLR_DETAILS();
}

void I2E_Init_StubWithCallback(CMOCK_I2E_Init_CALLBACK Callback)
{
  Mock.I2E_Init_CallbackFunctionPointer = Callback;
}

ErrorCode_t I2E_Read(uint32_t address, uint8_t* data, uint8_t numBytes)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_I2E_Read);
  CMOCK_I2E_Read_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2E_Read_CallInstance);
  Mock.I2E_Read_CallInstance = CMock_Guts_MemNext(Mock.I2E_Read_CallInstance);
  if (Mock.I2E_Read_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.I2E_Read_FinalReturn;
    memcpy(&Mock.I2E_Read_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(ErrorCode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.I2E_Read_CallbackFunctionPointer != NULL)
  {
    return Mock.I2E_Read_CallbackFunctionPointer(address, data, numBytes, Mock.I2E_Read_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_address)
  {
    UNITY_SET_DETAILS(CMockString_I2E_Read,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_address, address, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_data)
  {
    UNITY_SET_DETAILS(CMockString_I2E_Read,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, cmock_call_instance->Expected_data_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_numBytes)
  {
    UNITY_SET_DETAILS(CMockString_I2E_Read,CMockString_numBytes);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_numBytes, numBytes, cmock_line, CMockStringMismatch);
  }

  }
  if (cmock_call_instance->ReturnThruPtr_data_Used)
  {
    memcpy(data, cmock_call_instance->ReturnThruPtr_data_Val,
      cmock_call_instance->ReturnThruPtr_data_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_I2E_Read(CMOCK_I2E_Read_CALL_INSTANCE* cmock_call_instance, uint32_t address, uint8_t* data, int data_Depth, uint8_t numBytes)
{
  cmock_call_instance->Expected_address = address;
  cmock_call_instance->IgnoreArg_address = 0;
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_data_Depth = data_Depth;
  cmock_call_instance->IgnoreArg_data = 0;
  cmock_call_instance->ReturnThruPtr_data_Used = 0;
  cmock_call_instance->Expected_numBytes = numBytes;
  cmock_call_instance->IgnoreArg_numBytes = 0;
}

void I2E_Read_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2E_Read_CALL_INSTANCE));
  CMOCK_I2E_Read_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2E_Read_CallInstance = CMock_Guts_MemChain(Mock.I2E_Read_CallInstance, cmock_guts_index);
  Mock.I2E_Read_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.I2E_Read_IgnoreBool = (int)1;
}

void I2E_Read_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2E_Read_CALL_INSTANCE));
  CMOCK_I2E_Read_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2E_Read_CallInstance = CMock_Guts_MemChain(Mock.I2E_Read_CallInstance, cmock_guts_index);
  Mock.I2E_Read_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void I2E_Read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t address, uint8_t* data, uint8_t numBytes, ErrorCode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2E_Read_CALL_INSTANCE));
  CMOCK_I2E_Read_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2E_Read_CallInstance = CMock_Guts_MemChain(Mock.I2E_Read_CallInstance, cmock_guts_index);
  Mock.I2E_Read_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_I2E_Read(cmock_call_instance, address, data, 1, numBytes);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(ErrorCode_t));
  UNITY_CLR_DETAILS();
}

void I2E_Read_StubWithCallback(CMOCK_I2E_Read_CALLBACK Callback)
{
  Mock.I2E_Read_CallbackFunctionPointer = Callback;
}

void I2E_Read_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t address, uint8_t* data, int data_Depth, uint8_t numBytes, ErrorCode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2E_Read_CALL_INSTANCE));
  CMOCK_I2E_Read_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2E_Read_CallInstance = CMock_Guts_MemChain(Mock.I2E_Read_CallInstance, cmock_guts_index);
  Mock.I2E_Read_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_I2E_Read(cmock_call_instance, address, data, data_Depth, numBytes);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void I2E_Read_CMockReturnMemThruPtr_data(UNITY_LINE_TYPE cmock_line, uint8_t* data, int cmock_size)
{
  CMOCK_I2E_Read_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2E_Read_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_data_Used = 1;
  cmock_call_instance->ReturnThruPtr_data_Val = data;
  cmock_call_instance->ReturnThruPtr_data_Size = cmock_size;
}

void I2E_Read_CMockIgnoreArg_address(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2E_Read_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2E_Read_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_address = 1;
}

void I2E_Read_CMockIgnoreArg_data(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2E_Read_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2E_Read_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data = 1;
}

void I2E_Read_CMockIgnoreArg_numBytes(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2E_Read_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2E_Read_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_numBytes = 1;
}

ErrorCode_t I2E_Write(uint32_t address, const uint8_t* data, uint8_t numBytes)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_I2E_Write);
  CMOCK_I2E_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2E_Write_CallInstance);
  Mock.I2E_Write_CallInstance = CMock_Guts_MemNext(Mock.I2E_Write_CallInstance);
  if (Mock.I2E_Write_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.I2E_Write_FinalReturn;
    memcpy(&Mock.I2E_Write_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(ErrorCode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.I2E_Write_CallbackFunctionPointer != NULL)
  {
    return Mock.I2E_Write_CallbackFunctionPointer(address, data, numBytes, Mock.I2E_Write_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_address)
  {
    UNITY_SET_DETAILS(CMockString_I2E_Write,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_address, address, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_data)
  {
    UNITY_SET_DETAILS(CMockString_I2E_Write,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, cmock_call_instance->Expected_data_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_numBytes)
  {
    UNITY_SET_DETAILS(CMockString_I2E_Write,CMockString_numBytes);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_numBytes, numBytes, cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_I2E_Write(CMOCK_I2E_Write_CALL_INSTANCE* cmock_call_instance, uint32_t address, const uint8_t* data, int data_Depth, uint8_t numBytes)
{
  cmock_call_instance->Expected_address = address;
  cmock_call_instance->IgnoreArg_address = 0;
  cmock_call_instance->Expected_data = (uint8_t*)data;
  cmock_call_instance->Expected_data_Depth = data_Depth;
  cmock_call_instance->IgnoreArg_data = 0;
  cmock_call_instance->Expected_numBytes = numBytes;
  cmock_call_instance->IgnoreArg_numBytes = 0;
}

void I2E_Write_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2E_Write_CALL_INSTANCE));
  CMOCK_I2E_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2E_Write_CallInstance = CMock_Guts_MemChain(Mock.I2E_Write_CallInstance, cmock_guts_index);
  Mock.I2E_Write_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.I2E_Write_IgnoreBool = (int)1;
}

void I2E_Write_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2E_Write_CALL_INSTANCE));
  CMOCK_I2E_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2E_Write_CallInstance = CMock_Guts_MemChain(Mock.I2E_Write_CallInstance, cmock_guts_index);
  Mock.I2E_Write_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void I2E_Write_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t address, const uint8_t* data, uint8_t numBytes, ErrorCode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2E_Write_CALL_INSTANCE));
  CMOCK_I2E_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2E_Write_CallInstance = CMock_Guts_MemChain(Mock.I2E_Write_CallInstance, cmock_guts_index);
  Mock.I2E_Write_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_I2E_Write(cmock_call_instance, address, data, 1, numBytes);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(ErrorCode_t));
  UNITY_CLR_DETAILS();
}

void I2E_Write_StubWithCallback(CMOCK_I2E_Write_CALLBACK Callback)
{
  Mock.I2E_Write_CallbackFunctionPointer = Callback;
}

void I2E_Write_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t address, const uint8_t* data, int data_Depth, uint8_t numBytes, ErrorCode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2E_Write_CALL_INSTANCE));
  CMOCK_I2E_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2E_Write_CallInstance = CMock_Guts_MemChain(Mock.I2E_Write_CallInstance, cmock_guts_index);
  Mock.I2E_Write_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_I2E_Write(cmock_call_instance, address, data, data_Depth, numBytes);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void I2E_Write_CMockIgnoreArg_address(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2E_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2E_Write_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_address = 1;
}

void I2E_Write_CMockIgnoreArg_data(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2E_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2E_Write_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data = 1;
}

void I2E_Write_CMockIgnoreArg_numBytes(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2E_Write_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2E_Write_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2E_Write_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_numBytes = 1;
}

