/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockPressure_Part4.h"

static const char* CMockString_DataAddress = "DataAddress";
static const char* CMockString_DataBuffer = "DataBuffer";
static const char* CMockString_DataLength = "DataLength";
static const char* CMockString_Device = "Device";
static const char* CMockString_PM_ReadPressureSensors = "PM_ReadPressureSensors";
static const char* CMockString_PM_WritePressureSensors = "PM_WritePressureSensors";

typedef struct _CMOCK_PM_WritePressureSensors_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  bool_t ReturnVal;
  int CallOrder;
  uint8_t Expected_Device;
  uint8_t Expected_DataLength;
  uint8_t* Expected_DataBuffer;
  int Expected_DataBuffer_Depth;
  int ReturnThruPtr_DataBuffer_Used;
  uint8_t* ReturnThruPtr_DataBuffer_Val;
  int ReturnThruPtr_DataBuffer_Size;
  int IgnoreArg_Device;
  int IgnoreArg_DataLength;
  int IgnoreArg_DataBuffer;

} CMOCK_PM_WritePressureSensors_CALL_INSTANCE;

typedef struct _CMOCK_PM_ReadPressureSensors_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  bool_t ReturnVal;
  int CallOrder;
  uint8_t Expected_Device;
  uint8_t Expected_DataLength;
  uint8_t Expected_DataAddress;
  uint8_t* Expected_DataBuffer;
  int Expected_DataBuffer_Depth;
  int ReturnThruPtr_DataBuffer_Used;
  uint8_t* ReturnThruPtr_DataBuffer_Val;
  int ReturnThruPtr_DataBuffer_Size;
  int IgnoreArg_Device;
  int IgnoreArg_DataLength;
  int IgnoreArg_DataAddress;
  int IgnoreArg_DataBuffer;

} CMOCK_PM_ReadPressureSensors_CALL_INSTANCE;

static struct MockPressure_Part4Instance
{
  int PM_WritePressureSensors_IgnoreBool;
  bool_t PM_WritePressureSensors_FinalReturn;
  CMOCK_PM_WritePressureSensors_CALLBACK PM_WritePressureSensors_CallbackFunctionPointer;
  int PM_WritePressureSensors_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE PM_WritePressureSensors_CallInstance;
  int PM_ReadPressureSensors_IgnoreBool;
  bool_t PM_ReadPressureSensors_FinalReturn;
  CMOCK_PM_ReadPressureSensors_CALLBACK PM_ReadPressureSensors_CallbackFunctionPointer;
  int PM_ReadPressureSensors_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE PM_ReadPressureSensors_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void MockPressure_Part4_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.PM_WritePressureSensors_IgnoreBool)
    Mock.PM_WritePressureSensors_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_PM_WritePressureSensors);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.PM_WritePressureSensors_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.PM_WritePressureSensors_CallbackFunctionPointer != NULL)
    Mock.PM_WritePressureSensors_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.PM_ReadPressureSensors_IgnoreBool)
    Mock.PM_ReadPressureSensors_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_PM_ReadPressureSensors);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.PM_ReadPressureSensors_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.PM_ReadPressureSensors_CallbackFunctionPointer != NULL)
    Mock.PM_ReadPressureSensors_CallInstance = CMOCK_GUTS_NONE;
}

void MockPressure_Part4_Init(void)
{
  MockPressure_Part4_Destroy();
}

void MockPressure_Part4_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.PM_WritePressureSensors_CallbackFunctionPointer = NULL;
  Mock.PM_WritePressureSensors_CallbackCalls = 0;
  Mock.PM_ReadPressureSensors_CallbackFunctionPointer = NULL;
  Mock.PM_ReadPressureSensors_CallbackCalls = 0;
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

bool_t PM_WritePressureSensors(uint8_t Device, uint8_t DataLength, uint8_t* DataBuffer)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_PM_WritePressureSensors);
  CMOCK_PM_WritePressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_WritePressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.PM_WritePressureSensors_CallInstance);
  Mock.PM_WritePressureSensors_CallInstance = CMock_Guts_MemNext(Mock.PM_WritePressureSensors_CallInstance);
  if (Mock.PM_WritePressureSensors_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.PM_WritePressureSensors_FinalReturn;
    Mock.PM_WritePressureSensors_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.PM_WritePressureSensors_CallbackFunctionPointer != NULL)
  {
    return Mock.PM_WritePressureSensors_CallbackFunctionPointer(Device, DataLength, DataBuffer, Mock.PM_WritePressureSensors_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_Device)
  {
    UNITY_SET_DETAILS(CMockString_PM_WritePressureSensors,CMockString_Device);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_Device, Device, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_DataLength)
  {
    UNITY_SET_DETAILS(CMockString_PM_WritePressureSensors,CMockString_DataLength);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_DataLength, DataLength, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_DataBuffer)
  {
    UNITY_SET_DETAILS(CMockString_PM_WritePressureSensors,CMockString_DataBuffer);
    if (cmock_call_instance->Expected_DataBuffer == NULL)
      { UNITY_TEST_ASSERT_NULL(DataBuffer, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_DataBuffer, DataBuffer, cmock_call_instance->Expected_DataBuffer_Depth, cmock_line, CMockStringMismatch); }
  }

  }
  if (cmock_call_instance->ReturnThruPtr_DataBuffer_Used)
  {
    memcpy(DataBuffer, cmock_call_instance->ReturnThruPtr_DataBuffer_Val,
      cmock_call_instance->ReturnThruPtr_DataBuffer_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_PM_WritePressureSensors(CMOCK_PM_WritePressureSensors_CALL_INSTANCE* cmock_call_instance, uint8_t Device, uint8_t DataLength, uint8_t* DataBuffer, int DataBuffer_Depth)
{
  cmock_call_instance->Expected_Device = Device;
  cmock_call_instance->IgnoreArg_Device = 0;
  cmock_call_instance->Expected_DataLength = DataLength;
  cmock_call_instance->IgnoreArg_DataLength = 0;
  cmock_call_instance->Expected_DataBuffer = DataBuffer;
  cmock_call_instance->Expected_DataBuffer_Depth = DataBuffer_Depth;
  cmock_call_instance->IgnoreArg_DataBuffer = 0;
  cmock_call_instance->ReturnThruPtr_DataBuffer_Used = 0;
}

void PM_WritePressureSensors_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PM_WritePressureSensors_CALL_INSTANCE));
  CMOCK_PM_WritePressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_WritePressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PM_WritePressureSensors_CallInstance = CMock_Guts_MemChain(Mock.PM_WritePressureSensors_CallInstance, cmock_guts_index);
  Mock.PM_WritePressureSensors_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.PM_WritePressureSensors_IgnoreBool = (int)1;
}

void PM_WritePressureSensors_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PM_WritePressureSensors_CALL_INSTANCE));
  CMOCK_PM_WritePressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_WritePressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PM_WritePressureSensors_CallInstance = CMock_Guts_MemChain(Mock.PM_WritePressureSensors_CallInstance, cmock_guts_index);
  Mock.PM_WritePressureSensors_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void PM_WritePressureSensors_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t Device, uint8_t DataLength, uint8_t* DataBuffer, bool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PM_WritePressureSensors_CALL_INSTANCE));
  CMOCK_PM_WritePressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_WritePressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PM_WritePressureSensors_CallInstance = CMock_Guts_MemChain(Mock.PM_WritePressureSensors_CallInstance, cmock_guts_index);
  Mock.PM_WritePressureSensors_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_PM_WritePressureSensors(cmock_call_instance, Device, DataLength, DataBuffer, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void PM_WritePressureSensors_StubWithCallback(CMOCK_PM_WritePressureSensors_CALLBACK Callback)
{
  Mock.PM_WritePressureSensors_CallbackFunctionPointer = Callback;
}

void PM_WritePressureSensors_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t Device, uint8_t DataLength, uint8_t* DataBuffer, int DataBuffer_Depth, bool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PM_WritePressureSensors_CALL_INSTANCE));
  CMOCK_PM_WritePressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_WritePressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PM_WritePressureSensors_CallInstance = CMock_Guts_MemChain(Mock.PM_WritePressureSensors_CallInstance, cmock_guts_index);
  Mock.PM_WritePressureSensors_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_PM_WritePressureSensors(cmock_call_instance, Device, DataLength, DataBuffer, DataBuffer_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void PM_WritePressureSensors_CMockReturnMemThruPtr_DataBuffer(UNITY_LINE_TYPE cmock_line, uint8_t* DataBuffer, int cmock_size)
{
  CMOCK_PM_WritePressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_WritePressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PM_WritePressureSensors_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_DataBuffer_Used = 1;
  cmock_call_instance->ReturnThruPtr_DataBuffer_Val = DataBuffer;
  cmock_call_instance->ReturnThruPtr_DataBuffer_Size = cmock_size;
}

void PM_WritePressureSensors_CMockIgnoreArg_Device(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PM_WritePressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_WritePressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PM_WritePressureSensors_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_Device = 1;
}

void PM_WritePressureSensors_CMockIgnoreArg_DataLength(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PM_WritePressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_WritePressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PM_WritePressureSensors_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_DataLength = 1;
}

void PM_WritePressureSensors_CMockIgnoreArg_DataBuffer(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PM_WritePressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_WritePressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PM_WritePressureSensors_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_DataBuffer = 1;
}

bool_t PM_ReadPressureSensors(uint8_t Device, uint8_t DataLength, uint8_t DataAddress, uint8_t* DataBuffer)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_PM_ReadPressureSensors);
  CMOCK_PM_ReadPressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_ReadPressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.PM_ReadPressureSensors_CallInstance);
  Mock.PM_ReadPressureSensors_CallInstance = CMock_Guts_MemNext(Mock.PM_ReadPressureSensors_CallInstance);
  if (Mock.PM_ReadPressureSensors_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.PM_ReadPressureSensors_FinalReturn;
    Mock.PM_ReadPressureSensors_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.PM_ReadPressureSensors_CallbackFunctionPointer != NULL)
  {
    return Mock.PM_ReadPressureSensors_CallbackFunctionPointer(Device, DataLength, DataAddress, DataBuffer, Mock.PM_ReadPressureSensors_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_Device)
  {
    UNITY_SET_DETAILS(CMockString_PM_ReadPressureSensors,CMockString_Device);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_Device, Device, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_DataLength)
  {
    UNITY_SET_DETAILS(CMockString_PM_ReadPressureSensors,CMockString_DataLength);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_DataLength, DataLength, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_DataAddress)
  {
    UNITY_SET_DETAILS(CMockString_PM_ReadPressureSensors,CMockString_DataAddress);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_DataAddress, DataAddress, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_DataBuffer)
  {
    UNITY_SET_DETAILS(CMockString_PM_ReadPressureSensors,CMockString_DataBuffer);
    if (cmock_call_instance->Expected_DataBuffer == NULL)
      { UNITY_TEST_ASSERT_NULL(DataBuffer, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_DataBuffer, DataBuffer, cmock_call_instance->Expected_DataBuffer_Depth, cmock_line, CMockStringMismatch); }
  }

  }
  if (cmock_call_instance->ReturnThruPtr_DataBuffer_Used)
  {
    memcpy(DataBuffer, cmock_call_instance->ReturnThruPtr_DataBuffer_Val,
      cmock_call_instance->ReturnThruPtr_DataBuffer_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_PM_ReadPressureSensors(CMOCK_PM_ReadPressureSensors_CALL_INSTANCE* cmock_call_instance, uint8_t Device, uint8_t DataLength, uint8_t DataAddress, uint8_t* DataBuffer, int DataBuffer_Depth)
{
  cmock_call_instance->Expected_Device = Device;
  cmock_call_instance->IgnoreArg_Device = 0;
  cmock_call_instance->Expected_DataLength = DataLength;
  cmock_call_instance->IgnoreArg_DataLength = 0;
  cmock_call_instance->Expected_DataAddress = DataAddress;
  cmock_call_instance->IgnoreArg_DataAddress = 0;
  cmock_call_instance->Expected_DataBuffer = DataBuffer;
  cmock_call_instance->Expected_DataBuffer_Depth = DataBuffer_Depth;
  cmock_call_instance->IgnoreArg_DataBuffer = 0;
  cmock_call_instance->ReturnThruPtr_DataBuffer_Used = 0;
}

void PM_ReadPressureSensors_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PM_ReadPressureSensors_CALL_INSTANCE));
  CMOCK_PM_ReadPressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_ReadPressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PM_ReadPressureSensors_CallInstance = CMock_Guts_MemChain(Mock.PM_ReadPressureSensors_CallInstance, cmock_guts_index);
  Mock.PM_ReadPressureSensors_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.PM_ReadPressureSensors_IgnoreBool = (int)1;
}

void PM_ReadPressureSensors_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PM_ReadPressureSensors_CALL_INSTANCE));
  CMOCK_PM_ReadPressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_ReadPressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PM_ReadPressureSensors_CallInstance = CMock_Guts_MemChain(Mock.PM_ReadPressureSensors_CallInstance, cmock_guts_index);
  Mock.PM_ReadPressureSensors_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void PM_ReadPressureSensors_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t Device, uint8_t DataLength, uint8_t DataAddress, uint8_t* DataBuffer, bool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PM_ReadPressureSensors_CALL_INSTANCE));
  CMOCK_PM_ReadPressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_ReadPressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PM_ReadPressureSensors_CallInstance = CMock_Guts_MemChain(Mock.PM_ReadPressureSensors_CallInstance, cmock_guts_index);
  Mock.PM_ReadPressureSensors_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_PM_ReadPressureSensors(cmock_call_instance, Device, DataLength, DataAddress, DataBuffer, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void PM_ReadPressureSensors_StubWithCallback(CMOCK_PM_ReadPressureSensors_CALLBACK Callback)
{
  Mock.PM_ReadPressureSensors_CallbackFunctionPointer = Callback;
}

void PM_ReadPressureSensors_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t Device, uint8_t DataLength, uint8_t DataAddress, uint8_t* DataBuffer, int DataBuffer_Depth, bool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_PM_ReadPressureSensors_CALL_INSTANCE));
  CMOCK_PM_ReadPressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_ReadPressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.PM_ReadPressureSensors_CallInstance = CMock_Guts_MemChain(Mock.PM_ReadPressureSensors_CallInstance, cmock_guts_index);
  Mock.PM_ReadPressureSensors_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_PM_ReadPressureSensors(cmock_call_instance, Device, DataLength, DataAddress, DataBuffer, DataBuffer_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void PM_ReadPressureSensors_CMockReturnMemThruPtr_DataBuffer(UNITY_LINE_TYPE cmock_line, uint8_t* DataBuffer, int cmock_size)
{
  CMOCK_PM_ReadPressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_ReadPressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PM_ReadPressureSensors_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_DataBuffer_Used = 1;
  cmock_call_instance->ReturnThruPtr_DataBuffer_Val = DataBuffer;
  cmock_call_instance->ReturnThruPtr_DataBuffer_Size = cmock_size;
}

void PM_ReadPressureSensors_CMockIgnoreArg_Device(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PM_ReadPressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_ReadPressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PM_ReadPressureSensors_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_Device = 1;
}

void PM_ReadPressureSensors_CMockIgnoreArg_DataLength(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PM_ReadPressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_ReadPressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PM_ReadPressureSensors_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_DataLength = 1;
}

void PM_ReadPressureSensors_CMockIgnoreArg_DataAddress(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PM_ReadPressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_ReadPressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PM_ReadPressureSensors_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_DataAddress = 1;
}

void PM_ReadPressureSensors_CMockIgnoreArg_DataBuffer(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_PM_ReadPressureSensors_CALL_INSTANCE* cmock_call_instance = (CMOCK_PM_ReadPressureSensors_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.PM_ReadPressureSensors_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_DataBuffer = 1;
}

