/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mocki2c.h"

static const char* CMockString_I2C_BusCollisionISR = "I2C_BusCollisionISR";
static const char* CMockString_I2C_ISR = "I2C_ISR";
static const char* CMockString_I2C_Initialize = "I2C_Initialize";
static const char* CMockString_I2C_MasterQueueIsEmpty = "I2C_MasterQueueIsEmpty";
static const char* CMockString_I2C_MasterQueueIsFull = "I2C_MasterQueueIsFull";
static const char* CMockString_I2C_MasterRead = "I2C_MasterRead";
static const char* CMockString_I2C_MasterReadTRBBuild = "I2C_MasterReadTRBBuild";
static const char* CMockString_I2C_MasterTRBInsert = "I2C_MasterTRBInsert";
static const char* CMockString_I2C_MasterWrite = "I2C_MasterWrite";
static const char* CMockString_I2C_MasterWriteTRBBuild = "I2C_MasterWriteTRBBuild";
static const char* CMockString_address = "address";
static const char* CMockString_count = "count";
static const char* CMockString_length = "length";
static const char* CMockString_pdata = "pdata";
static const char* CMockString_pflag = "pflag";
static const char* CMockString_pstatus = "pstatus";
static const char* CMockString_ptrb = "ptrb";
static const char* CMockString_ptrb_list = "ptrb_list";

typedef struct _CMOCK_I2C_Initialize_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int CallOrder;

} CMOCK_I2C_Initialize_CALL_INSTANCE;

typedef struct _CMOCK_I2C_MasterWrite_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int CallOrder;
  uint8_t* Expected_pdata;
  uint8_t Expected_length;
  uint16_t Expected_address;
  I2C_MESSAGE_STATUS* Expected_pstatus;
  int Expected_pdata_Depth;
  int Expected_pstatus_Depth;
  int ReturnThruPtr_pdata_Used;
  uint8_t* ReturnThruPtr_pdata_Val;
  int ReturnThruPtr_pdata_Size;
  int ReturnThruPtr_pstatus_Used;
  I2C_MESSAGE_STATUS* ReturnThruPtr_pstatus_Val;
  int ReturnThruPtr_pstatus_Size;
  int IgnoreArg_pdata;
  int IgnoreArg_length;
  int IgnoreArg_address;
  int IgnoreArg_pstatus;

} CMOCK_I2C_MasterWrite_CALL_INSTANCE;

typedef struct _CMOCK_I2C_MasterRead_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int CallOrder;
  uint8_t* Expected_pdata;
  uint8_t Expected_length;
  uint16_t Expected_address;
  I2C_MESSAGE_STATUS* Expected_pstatus;
  int Expected_pdata_Depth;
  int Expected_pstatus_Depth;
  int ReturnThruPtr_pdata_Used;
  uint8_t* ReturnThruPtr_pdata_Val;
  int ReturnThruPtr_pdata_Size;
  int ReturnThruPtr_pstatus_Used;
  I2C_MESSAGE_STATUS* ReturnThruPtr_pstatus_Val;
  int ReturnThruPtr_pstatus_Size;
  int IgnoreArg_pdata;
  int IgnoreArg_length;
  int IgnoreArg_address;
  int IgnoreArg_pstatus;

} CMOCK_I2C_MasterRead_CALL_INSTANCE;

typedef struct _CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int CallOrder;
  uint8_t Expected_count;
  I2C_TRANSACTION_REQUEST_BLOCK* Expected_ptrb_list;
  I2C_MESSAGE_STATUS* Expected_pflag;
  int Expected_ptrb_list_Depth;
  int Expected_pflag_Depth;
  int ReturnThruPtr_ptrb_list_Used;
  I2C_TRANSACTION_REQUEST_BLOCK* ReturnThruPtr_ptrb_list_Val;
  int ReturnThruPtr_ptrb_list_Size;
  int ReturnThruPtr_pflag_Used;
  I2C_MESSAGE_STATUS* ReturnThruPtr_pflag_Val;
  int ReturnThruPtr_pflag_Size;
  int IgnoreArg_count;
  int IgnoreArg_ptrb_list;
  int IgnoreArg_pflag;

} CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE;

typedef struct _CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int CallOrder;
  I2C_TRANSACTION_REQUEST_BLOCK* Expected_ptrb;
  uint8_t* Expected_pdata;
  uint8_t Expected_length;
  uint16_t Expected_address;
  int Expected_ptrb_Depth;
  int Expected_pdata_Depth;
  int ReturnThruPtr_ptrb_Used;
  I2C_TRANSACTION_REQUEST_BLOCK* ReturnThruPtr_ptrb_Val;
  int ReturnThruPtr_ptrb_Size;
  int ReturnThruPtr_pdata_Used;
  uint8_t* ReturnThruPtr_pdata_Val;
  int ReturnThruPtr_pdata_Size;
  int IgnoreArg_ptrb;
  int IgnoreArg_pdata;
  int IgnoreArg_length;
  int IgnoreArg_address;

} CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE;

typedef struct _CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int CallOrder;
  I2C_TRANSACTION_REQUEST_BLOCK* Expected_ptrb;
  uint8_t* Expected_pdata;
  uint8_t Expected_length;
  uint16_t Expected_address;
  int Expected_ptrb_Depth;
  int Expected_pdata_Depth;
  int ReturnThruPtr_ptrb_Used;
  I2C_TRANSACTION_REQUEST_BLOCK* ReturnThruPtr_ptrb_Val;
  int ReturnThruPtr_ptrb_Size;
  int ReturnThruPtr_pdata_Used;
  uint8_t* ReturnThruPtr_pdata_Val;
  int ReturnThruPtr_pdata_Size;
  int IgnoreArg_ptrb;
  int IgnoreArg_pdata;
  int IgnoreArg_length;
  int IgnoreArg_address;

} CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE;

typedef struct _CMOCK_I2C_MasterQueueIsEmpty_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  _Bool ReturnVal;
  int CallOrder;

} CMOCK_I2C_MasterQueueIsEmpty_CALL_INSTANCE;

typedef struct _CMOCK_I2C_MasterQueueIsFull_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  _Bool ReturnVal;
  int CallOrder;

} CMOCK_I2C_MasterQueueIsFull_CALL_INSTANCE;

typedef struct _CMOCK_I2C_BusCollisionISR_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int CallOrder;

} CMOCK_I2C_BusCollisionISR_CALL_INSTANCE;

typedef struct _CMOCK_I2C_ISR_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int CallOrder;

} CMOCK_I2C_ISR_CALL_INSTANCE;

static struct Mocki2cInstance
{
  int I2C_Initialize_IgnoreBool;
  CMOCK_I2C_Initialize_CALLBACK I2C_Initialize_CallbackFunctionPointer;
  int I2C_Initialize_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE I2C_Initialize_CallInstance;
  int I2C_MasterWrite_IgnoreBool;
  CMOCK_I2C_MasterWrite_CALLBACK I2C_MasterWrite_CallbackFunctionPointer;
  int I2C_MasterWrite_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE I2C_MasterWrite_CallInstance;
  int I2C_MasterRead_IgnoreBool;
  CMOCK_I2C_MasterRead_CALLBACK I2C_MasterRead_CallbackFunctionPointer;
  int I2C_MasterRead_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE I2C_MasterRead_CallInstance;
  int I2C_MasterTRBInsert_IgnoreBool;
  CMOCK_I2C_MasterTRBInsert_CALLBACK I2C_MasterTRBInsert_CallbackFunctionPointer;
  int I2C_MasterTRBInsert_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE I2C_MasterTRBInsert_CallInstance;
  int I2C_MasterReadTRBBuild_IgnoreBool;
  CMOCK_I2C_MasterReadTRBBuild_CALLBACK I2C_MasterReadTRBBuild_CallbackFunctionPointer;
  int I2C_MasterReadTRBBuild_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE I2C_MasterReadTRBBuild_CallInstance;
  int I2C_MasterWriteTRBBuild_IgnoreBool;
  CMOCK_I2C_MasterWriteTRBBuild_CALLBACK I2C_MasterWriteTRBBuild_CallbackFunctionPointer;
  int I2C_MasterWriteTRBBuild_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE I2C_MasterWriteTRBBuild_CallInstance;
  int I2C_MasterQueueIsEmpty_IgnoreBool;
  _Bool I2C_MasterQueueIsEmpty_FinalReturn;
  CMOCK_I2C_MasterQueueIsEmpty_CALLBACK I2C_MasterQueueIsEmpty_CallbackFunctionPointer;
  int I2C_MasterQueueIsEmpty_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE I2C_MasterQueueIsEmpty_CallInstance;
  int I2C_MasterQueueIsFull_IgnoreBool;
  _Bool I2C_MasterQueueIsFull_FinalReturn;
  CMOCK_I2C_MasterQueueIsFull_CALLBACK I2C_MasterQueueIsFull_CallbackFunctionPointer;
  int I2C_MasterQueueIsFull_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE I2C_MasterQueueIsFull_CallInstance;
  int I2C_BusCollisionISR_IgnoreBool;
  CMOCK_I2C_BusCollisionISR_CALLBACK I2C_BusCollisionISR_CallbackFunctionPointer;
  int I2C_BusCollisionISR_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE I2C_BusCollisionISR_CallInstance;
  int I2C_ISR_IgnoreBool;
  CMOCK_I2C_ISR_CALLBACK I2C_ISR_CallbackFunctionPointer;
  int I2C_ISR_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE I2C_ISR_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void Mocki2c_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.I2C_Initialize_IgnoreBool)
    Mock.I2C_Initialize_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_I2C_Initialize);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.I2C_Initialize_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.I2C_Initialize_CallbackFunctionPointer != NULL)
    Mock.I2C_Initialize_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.I2C_MasterWrite_IgnoreBool)
    Mock.I2C_MasterWrite_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_I2C_MasterWrite);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.I2C_MasterWrite_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.I2C_MasterWrite_CallbackFunctionPointer != NULL)
    Mock.I2C_MasterWrite_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.I2C_MasterRead_IgnoreBool)
    Mock.I2C_MasterRead_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_I2C_MasterRead);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.I2C_MasterRead_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.I2C_MasterRead_CallbackFunctionPointer != NULL)
    Mock.I2C_MasterRead_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.I2C_MasterTRBInsert_IgnoreBool)
    Mock.I2C_MasterTRBInsert_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_I2C_MasterTRBInsert);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.I2C_MasterTRBInsert_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.I2C_MasterTRBInsert_CallbackFunctionPointer != NULL)
    Mock.I2C_MasterTRBInsert_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.I2C_MasterReadTRBBuild_IgnoreBool)
    Mock.I2C_MasterReadTRBBuild_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_I2C_MasterReadTRBBuild);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.I2C_MasterReadTRBBuild_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.I2C_MasterReadTRBBuild_CallbackFunctionPointer != NULL)
    Mock.I2C_MasterReadTRBBuild_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.I2C_MasterWriteTRBBuild_IgnoreBool)
    Mock.I2C_MasterWriteTRBBuild_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_I2C_MasterWriteTRBBuild);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.I2C_MasterWriteTRBBuild_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.I2C_MasterWriteTRBBuild_CallbackFunctionPointer != NULL)
    Mock.I2C_MasterWriteTRBBuild_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.I2C_MasterQueueIsEmpty_IgnoreBool)
    Mock.I2C_MasterQueueIsEmpty_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_I2C_MasterQueueIsEmpty);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.I2C_MasterQueueIsEmpty_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.I2C_MasterQueueIsEmpty_CallbackFunctionPointer != NULL)
    Mock.I2C_MasterQueueIsEmpty_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.I2C_MasterQueueIsFull_IgnoreBool)
    Mock.I2C_MasterQueueIsFull_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_I2C_MasterQueueIsFull);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.I2C_MasterQueueIsFull_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.I2C_MasterQueueIsFull_CallbackFunctionPointer != NULL)
    Mock.I2C_MasterQueueIsFull_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.I2C_BusCollisionISR_IgnoreBool)
    Mock.I2C_BusCollisionISR_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_I2C_BusCollisionISR);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.I2C_BusCollisionISR_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.I2C_BusCollisionISR_CallbackFunctionPointer != NULL)
    Mock.I2C_BusCollisionISR_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.I2C_ISR_IgnoreBool)
    Mock.I2C_ISR_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_I2C_ISR);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.I2C_ISR_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.I2C_ISR_CallbackFunctionPointer != NULL)
    Mock.I2C_ISR_CallInstance = CMOCK_GUTS_NONE;
}

void Mocki2c_Init(void)
{
  Mocki2c_Destroy();
}

void Mocki2c_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.I2C_Initialize_CallbackFunctionPointer = NULL;
  Mock.I2C_Initialize_CallbackCalls = 0;
  Mock.I2C_MasterWrite_CallbackFunctionPointer = NULL;
  Mock.I2C_MasterWrite_CallbackCalls = 0;
  Mock.I2C_MasterRead_CallbackFunctionPointer = NULL;
  Mock.I2C_MasterRead_CallbackCalls = 0;
  Mock.I2C_MasterTRBInsert_CallbackFunctionPointer = NULL;
  Mock.I2C_MasterTRBInsert_CallbackCalls = 0;
  Mock.I2C_MasterReadTRBBuild_CallbackFunctionPointer = NULL;
  Mock.I2C_MasterReadTRBBuild_CallbackCalls = 0;
  Mock.I2C_MasterWriteTRBBuild_CallbackFunctionPointer = NULL;
  Mock.I2C_MasterWriteTRBBuild_CallbackCalls = 0;
  Mock.I2C_MasterQueueIsEmpty_CallbackFunctionPointer = NULL;
  Mock.I2C_MasterQueueIsEmpty_CallbackCalls = 0;
  Mock.I2C_MasterQueueIsFull_CallbackFunctionPointer = NULL;
  Mock.I2C_MasterQueueIsFull_CallbackCalls = 0;
  Mock.I2C_BusCollisionISR_CallbackFunctionPointer = NULL;
  Mock.I2C_BusCollisionISR_CallbackCalls = 0;
  Mock.I2C_ISR_CallbackFunctionPointer = NULL;
  Mock.I2C_ISR_CallbackCalls = 0;
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void I2C_Initialize(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_I2C_Initialize);
  CMOCK_I2C_Initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_Initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C_Initialize_CallInstance);
  Mock.I2C_Initialize_CallInstance = CMock_Guts_MemNext(Mock.I2C_Initialize_CallInstance);
  if (Mock.I2C_Initialize_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.I2C_Initialize_CallbackFunctionPointer != NULL)
  {
    Mock.I2C_Initialize_CallbackFunctionPointer(Mock.I2C_Initialize_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  UNITY_CLR_DETAILS();
}

void I2C_Initialize_CMockIgnore(void)
{
  Mock.I2C_Initialize_IgnoreBool = (int)1;
}

void I2C_Initialize_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_Initialize_CALL_INSTANCE));
  CMOCK_I2C_Initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_Initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_Initialize_CallInstance = CMock_Guts_MemChain(Mock.I2C_Initialize_CallInstance, cmock_guts_index);
  Mock.I2C_Initialize_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void I2C_Initialize_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_Initialize_CALL_INSTANCE));
  CMOCK_I2C_Initialize_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_Initialize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_Initialize_CallInstance = CMock_Guts_MemChain(Mock.I2C_Initialize_CallInstance, cmock_guts_index);
  Mock.I2C_Initialize_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  UNITY_CLR_DETAILS();
}

void I2C_Initialize_StubWithCallback(CMOCK_I2C_Initialize_CALLBACK Callback)
{
  Mock.I2C_Initialize_CallbackFunctionPointer = Callback;
}

void I2C_MasterWrite(uint8_t* pdata, uint8_t length, uint16_t address, I2C_MESSAGE_STATUS* pstatus)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_I2C_MasterWrite);
  CMOCK_I2C_MasterWrite_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C_MasterWrite_CallInstance);
  Mock.I2C_MasterWrite_CallInstance = CMock_Guts_MemNext(Mock.I2C_MasterWrite_CallInstance);
  if (Mock.I2C_MasterWrite_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.I2C_MasterWrite_CallbackFunctionPointer != NULL)
  {
    Mock.I2C_MasterWrite_CallbackFunctionPointer(pdata, length, address, pstatus, Mock.I2C_MasterWrite_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_pdata)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterWrite,CMockString_pdata);
    if (cmock_call_instance->Expected_pdata == NULL)
      { UNITY_TEST_ASSERT_NULL(pdata, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_pdata, pdata, cmock_call_instance->Expected_pdata_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_length)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterWrite,CMockString_length);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_length, length, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_address)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterWrite,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_address, address, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_pstatus)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterWrite,CMockString_pstatus);
    if (cmock_call_instance->Expected_pstatus == NULL)
      { UNITY_TEST_ASSERT_NULL(pstatus, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_pstatus), (void*)(pstatus), sizeof(I2C_MESSAGE_STATUS), cmock_call_instance->Expected_pstatus_Depth, cmock_line, CMockStringMismatch); }
  }

  }
  if (cmock_call_instance->ReturnThruPtr_pdata_Used)
  {
    memcpy(pdata, cmock_call_instance->ReturnThruPtr_pdata_Val,
      cmock_call_instance->ReturnThruPtr_pdata_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_pstatus_Used)
  {
    memcpy(pstatus, cmock_call_instance->ReturnThruPtr_pstatus_Val,
      cmock_call_instance->ReturnThruPtr_pstatus_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_I2C_MasterWrite(CMOCK_I2C_MasterWrite_CALL_INSTANCE* cmock_call_instance, uint8_t* pdata, int pdata_Depth, uint8_t length, uint16_t address, I2C_MESSAGE_STATUS* pstatus, int pstatus_Depth)
{
  cmock_call_instance->Expected_pdata = pdata;
  cmock_call_instance->Expected_pdata_Depth = pdata_Depth;
  cmock_call_instance->IgnoreArg_pdata = 0;
  cmock_call_instance->ReturnThruPtr_pdata_Used = 0;
  cmock_call_instance->Expected_length = length;
  cmock_call_instance->IgnoreArg_length = 0;
  cmock_call_instance->Expected_address = address;
  cmock_call_instance->IgnoreArg_address = 0;
  cmock_call_instance->Expected_pstatus = pstatus;
  cmock_call_instance->Expected_pstatus_Depth = pstatus_Depth;
  cmock_call_instance->IgnoreArg_pstatus = 0;
  cmock_call_instance->ReturnThruPtr_pstatus_Used = 0;
}

void I2C_MasterWrite_CMockIgnore(void)
{
  Mock.I2C_MasterWrite_IgnoreBool = (int)1;
}

void I2C_MasterWrite_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterWrite_CALL_INSTANCE));
  CMOCK_I2C_MasterWrite_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterWrite_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterWrite_CallInstance, cmock_guts_index);
  Mock.I2C_MasterWrite_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void I2C_MasterWrite_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t* pdata, uint8_t length, uint16_t address, I2C_MESSAGE_STATUS* pstatus)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterWrite_CALL_INSTANCE));
  CMOCK_I2C_MasterWrite_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterWrite_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterWrite_CallInstance, cmock_guts_index);
  Mock.I2C_MasterWrite_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_I2C_MasterWrite(cmock_call_instance, pdata, 1, length, address, pstatus, 1);
  UNITY_CLR_DETAILS();
}

void I2C_MasterWrite_StubWithCallback(CMOCK_I2C_MasterWrite_CALLBACK Callback)
{
  Mock.I2C_MasterWrite_CallbackFunctionPointer = Callback;
}

void I2C_MasterWrite_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, uint8_t* pdata, int pdata_Depth, uint8_t length, uint16_t address, I2C_MESSAGE_STATUS* pstatus, int pstatus_Depth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterWrite_CALL_INSTANCE));
  CMOCK_I2C_MasterWrite_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterWrite_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterWrite_CallInstance, cmock_guts_index);
  Mock.I2C_MasterWrite_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_I2C_MasterWrite(cmock_call_instance, pdata, pdata_Depth, length, address, pstatus, pstatus_Depth);
}

void I2C_MasterWrite_CMockReturnMemThruPtr_pdata(UNITY_LINE_TYPE cmock_line, uint8_t* pdata, int cmock_size)
{
  CMOCK_I2C_MasterWrite_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterWrite_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_pdata_Used = 1;
  cmock_call_instance->ReturnThruPtr_pdata_Val = pdata;
  cmock_call_instance->ReturnThruPtr_pdata_Size = cmock_size;
}

void I2C_MasterWrite_CMockReturnMemThruPtr_pstatus(UNITY_LINE_TYPE cmock_line, I2C_MESSAGE_STATUS* pstatus, int cmock_size)
{
  CMOCK_I2C_MasterWrite_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterWrite_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_pstatus_Used = 1;
  cmock_call_instance->ReturnThruPtr_pstatus_Val = pstatus;
  cmock_call_instance->ReturnThruPtr_pstatus_Size = cmock_size;
}

void I2C_MasterWrite_CMockIgnoreArg_pdata(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterWrite_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterWrite_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pdata = 1;
}

void I2C_MasterWrite_CMockIgnoreArg_length(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterWrite_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterWrite_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_length = 1;
}

void I2C_MasterWrite_CMockIgnoreArg_address(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterWrite_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterWrite_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_address = 1;
}

void I2C_MasterWrite_CMockIgnoreArg_pstatus(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterWrite_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWrite_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterWrite_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pstatus = 1;
}

void I2C_MasterRead(uint8_t* pdata, uint8_t length, uint16_t address, I2C_MESSAGE_STATUS* pstatus)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_I2C_MasterRead);
  CMOCK_I2C_MasterRead_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterRead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C_MasterRead_CallInstance);
  Mock.I2C_MasterRead_CallInstance = CMock_Guts_MemNext(Mock.I2C_MasterRead_CallInstance);
  if (Mock.I2C_MasterRead_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.I2C_MasterRead_CallbackFunctionPointer != NULL)
  {
    Mock.I2C_MasterRead_CallbackFunctionPointer(pdata, length, address, pstatus, Mock.I2C_MasterRead_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_pdata)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterRead,CMockString_pdata);
    if (cmock_call_instance->Expected_pdata == NULL)
      { UNITY_TEST_ASSERT_NULL(pdata, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_pdata, pdata, cmock_call_instance->Expected_pdata_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_length)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterRead,CMockString_length);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_length, length, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_address)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterRead,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_address, address, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_pstatus)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterRead,CMockString_pstatus);
    if (cmock_call_instance->Expected_pstatus == NULL)
      { UNITY_TEST_ASSERT_NULL(pstatus, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_pstatus), (void*)(pstatus), sizeof(I2C_MESSAGE_STATUS), cmock_call_instance->Expected_pstatus_Depth, cmock_line, CMockStringMismatch); }
  }

  }
  if (cmock_call_instance->ReturnThruPtr_pdata_Used)
  {
    memcpy(pdata, cmock_call_instance->ReturnThruPtr_pdata_Val,
      cmock_call_instance->ReturnThruPtr_pdata_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_pstatus_Used)
  {
    memcpy(pstatus, cmock_call_instance->ReturnThruPtr_pstatus_Val,
      cmock_call_instance->ReturnThruPtr_pstatus_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_I2C_MasterRead(CMOCK_I2C_MasterRead_CALL_INSTANCE* cmock_call_instance, uint8_t* pdata, int pdata_Depth, uint8_t length, uint16_t address, I2C_MESSAGE_STATUS* pstatus, int pstatus_Depth)
{
  cmock_call_instance->Expected_pdata = pdata;
  cmock_call_instance->Expected_pdata_Depth = pdata_Depth;
  cmock_call_instance->IgnoreArg_pdata = 0;
  cmock_call_instance->ReturnThruPtr_pdata_Used = 0;
  cmock_call_instance->Expected_length = length;
  cmock_call_instance->IgnoreArg_length = 0;
  cmock_call_instance->Expected_address = address;
  cmock_call_instance->IgnoreArg_address = 0;
  cmock_call_instance->Expected_pstatus = pstatus;
  cmock_call_instance->Expected_pstatus_Depth = pstatus_Depth;
  cmock_call_instance->IgnoreArg_pstatus = 0;
  cmock_call_instance->ReturnThruPtr_pstatus_Used = 0;
}

void I2C_MasterRead_CMockIgnore(void)
{
  Mock.I2C_MasterRead_IgnoreBool = (int)1;
}

void I2C_MasterRead_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterRead_CALL_INSTANCE));
  CMOCK_I2C_MasterRead_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterRead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterRead_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterRead_CallInstance, cmock_guts_index);
  Mock.I2C_MasterRead_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void I2C_MasterRead_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t* pdata, uint8_t length, uint16_t address, I2C_MESSAGE_STATUS* pstatus)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterRead_CALL_INSTANCE));
  CMOCK_I2C_MasterRead_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterRead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterRead_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterRead_CallInstance, cmock_guts_index);
  Mock.I2C_MasterRead_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_I2C_MasterRead(cmock_call_instance, pdata, 1, length, address, pstatus, 1);
  UNITY_CLR_DETAILS();
}

void I2C_MasterRead_StubWithCallback(CMOCK_I2C_MasterRead_CALLBACK Callback)
{
  Mock.I2C_MasterRead_CallbackFunctionPointer = Callback;
}

void I2C_MasterRead_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, uint8_t* pdata, int pdata_Depth, uint8_t length, uint16_t address, I2C_MESSAGE_STATUS* pstatus, int pstatus_Depth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterRead_CALL_INSTANCE));
  CMOCK_I2C_MasterRead_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterRead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterRead_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterRead_CallInstance, cmock_guts_index);
  Mock.I2C_MasterRead_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_I2C_MasterRead(cmock_call_instance, pdata, pdata_Depth, length, address, pstatus, pstatus_Depth);
}

void I2C_MasterRead_CMockReturnMemThruPtr_pdata(UNITY_LINE_TYPE cmock_line, uint8_t* pdata, int cmock_size)
{
  CMOCK_I2C_MasterRead_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterRead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterRead_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_pdata_Used = 1;
  cmock_call_instance->ReturnThruPtr_pdata_Val = pdata;
  cmock_call_instance->ReturnThruPtr_pdata_Size = cmock_size;
}

void I2C_MasterRead_CMockReturnMemThruPtr_pstatus(UNITY_LINE_TYPE cmock_line, I2C_MESSAGE_STATUS* pstatus, int cmock_size)
{
  CMOCK_I2C_MasterRead_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterRead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterRead_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_pstatus_Used = 1;
  cmock_call_instance->ReturnThruPtr_pstatus_Val = pstatus;
  cmock_call_instance->ReturnThruPtr_pstatus_Size = cmock_size;
}

void I2C_MasterRead_CMockIgnoreArg_pdata(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterRead_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterRead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterRead_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pdata = 1;
}

void I2C_MasterRead_CMockIgnoreArg_length(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterRead_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterRead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterRead_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_length = 1;
}

void I2C_MasterRead_CMockIgnoreArg_address(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterRead_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterRead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterRead_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_address = 1;
}

void I2C_MasterRead_CMockIgnoreArg_pstatus(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterRead_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterRead_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterRead_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pstatus = 1;
}

void I2C_MasterTRBInsert(uint8_t count, I2C_TRANSACTION_REQUEST_BLOCK* ptrb_list, I2C_MESSAGE_STATUS* pflag)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_I2C_MasterTRBInsert);
  CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C_MasterTRBInsert_CallInstance);
  Mock.I2C_MasterTRBInsert_CallInstance = CMock_Guts_MemNext(Mock.I2C_MasterTRBInsert_CallInstance);
  if (Mock.I2C_MasterTRBInsert_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.I2C_MasterTRBInsert_CallbackFunctionPointer != NULL)
  {
    Mock.I2C_MasterTRBInsert_CallbackFunctionPointer(count, ptrb_list, pflag, Mock.I2C_MasterTRBInsert_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_count)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterTRBInsert,CMockString_count);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_count, count, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_ptrb_list)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterTRBInsert,CMockString_ptrb_list);
    if (cmock_call_instance->Expected_ptrb_list == NULL)
      { UNITY_TEST_ASSERT_NULL(ptrb_list, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_ptrb_list), (void*)(ptrb_list), sizeof(I2C_TRANSACTION_REQUEST_BLOCK), cmock_call_instance->Expected_ptrb_list_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_pflag)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterTRBInsert,CMockString_pflag);
    if (cmock_call_instance->Expected_pflag == NULL)
      { UNITY_TEST_ASSERT_NULL(pflag, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_pflag), (void*)(pflag), sizeof(I2C_MESSAGE_STATUS), cmock_call_instance->Expected_pflag_Depth, cmock_line, CMockStringMismatch); }
  }

  }
  if (cmock_call_instance->ReturnThruPtr_ptrb_list_Used)
  {
    memcpy(ptrb_list, cmock_call_instance->ReturnThruPtr_ptrb_list_Val,
      cmock_call_instance->ReturnThruPtr_ptrb_list_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_pflag_Used)
  {
    memcpy(pflag, cmock_call_instance->ReturnThruPtr_pflag_Val,
      cmock_call_instance->ReturnThruPtr_pflag_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_I2C_MasterTRBInsert(CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE* cmock_call_instance, uint8_t count, I2C_TRANSACTION_REQUEST_BLOCK* ptrb_list, int ptrb_list_Depth, I2C_MESSAGE_STATUS* pflag, int pflag_Depth)
{
  cmock_call_instance->Expected_count = count;
  cmock_call_instance->IgnoreArg_count = 0;
  cmock_call_instance->Expected_ptrb_list = ptrb_list;
  cmock_call_instance->Expected_ptrb_list_Depth = ptrb_list_Depth;
  cmock_call_instance->IgnoreArg_ptrb_list = 0;
  cmock_call_instance->ReturnThruPtr_ptrb_list_Used = 0;
  cmock_call_instance->Expected_pflag = pflag;
  cmock_call_instance->Expected_pflag_Depth = pflag_Depth;
  cmock_call_instance->IgnoreArg_pflag = 0;
  cmock_call_instance->ReturnThruPtr_pflag_Used = 0;
}

void I2C_MasterTRBInsert_CMockIgnore(void)
{
  Mock.I2C_MasterTRBInsert_IgnoreBool = (int)1;
}

void I2C_MasterTRBInsert_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE));
  CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterTRBInsert_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterTRBInsert_CallInstance, cmock_guts_index);
  Mock.I2C_MasterTRBInsert_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void I2C_MasterTRBInsert_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t count, I2C_TRANSACTION_REQUEST_BLOCK* ptrb_list, I2C_MESSAGE_STATUS* pflag)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE));
  CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterTRBInsert_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterTRBInsert_CallInstance, cmock_guts_index);
  Mock.I2C_MasterTRBInsert_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_I2C_MasterTRBInsert(cmock_call_instance, count, ptrb_list, 1, pflag, 1);
  UNITY_CLR_DETAILS();
}

void I2C_MasterTRBInsert_StubWithCallback(CMOCK_I2C_MasterTRBInsert_CALLBACK Callback)
{
  Mock.I2C_MasterTRBInsert_CallbackFunctionPointer = Callback;
}

void I2C_MasterTRBInsert_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, uint8_t count, I2C_TRANSACTION_REQUEST_BLOCK* ptrb_list, int ptrb_list_Depth, I2C_MESSAGE_STATUS* pflag, int pflag_Depth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE));
  CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterTRBInsert_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterTRBInsert_CallInstance, cmock_guts_index);
  Mock.I2C_MasterTRBInsert_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_I2C_MasterTRBInsert(cmock_call_instance, count, ptrb_list, ptrb_list_Depth, pflag, pflag_Depth);
}

void I2C_MasterTRBInsert_CMockReturnMemThruPtr_ptrb_list(UNITY_LINE_TYPE cmock_line, I2C_TRANSACTION_REQUEST_BLOCK* ptrb_list, int cmock_size)
{
  CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterTRBInsert_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_ptrb_list_Used = 1;
  cmock_call_instance->ReturnThruPtr_ptrb_list_Val = ptrb_list;
  cmock_call_instance->ReturnThruPtr_ptrb_list_Size = cmock_size;
}

void I2C_MasterTRBInsert_CMockReturnMemThruPtr_pflag(UNITY_LINE_TYPE cmock_line, I2C_MESSAGE_STATUS* pflag, int cmock_size)
{
  CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterTRBInsert_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_pflag_Used = 1;
  cmock_call_instance->ReturnThruPtr_pflag_Val = pflag;
  cmock_call_instance->ReturnThruPtr_pflag_Size = cmock_size;
}

void I2C_MasterTRBInsert_CMockIgnoreArg_count(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterTRBInsert_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_count = 1;
}

void I2C_MasterTRBInsert_CMockIgnoreArg_ptrb_list(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterTRBInsert_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_ptrb_list = 1;
}

void I2C_MasterTRBInsert_CMockIgnoreArg_pflag(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterTRBInsert_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterTRBInsert_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pflag = 1;
}

void I2C_MasterReadTRBBuild(I2C_TRANSACTION_REQUEST_BLOCK* ptrb, uint8_t* pdata, uint8_t length, uint16_t address)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_I2C_MasterReadTRBBuild);
  CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C_MasterReadTRBBuild_CallInstance);
  Mock.I2C_MasterReadTRBBuild_CallInstance = CMock_Guts_MemNext(Mock.I2C_MasterReadTRBBuild_CallInstance);
  if (Mock.I2C_MasterReadTRBBuild_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.I2C_MasterReadTRBBuild_CallbackFunctionPointer != NULL)
  {
    Mock.I2C_MasterReadTRBBuild_CallbackFunctionPointer(ptrb, pdata, length, address, Mock.I2C_MasterReadTRBBuild_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_ptrb)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterReadTRBBuild,CMockString_ptrb);
    if (cmock_call_instance->Expected_ptrb == NULL)
      { UNITY_TEST_ASSERT_NULL(ptrb, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_ptrb), (void*)(ptrb), sizeof(I2C_TRANSACTION_REQUEST_BLOCK), cmock_call_instance->Expected_ptrb_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_pdata)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterReadTRBBuild,CMockString_pdata);
    if (cmock_call_instance->Expected_pdata == NULL)
      { UNITY_TEST_ASSERT_NULL(pdata, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_pdata, pdata, cmock_call_instance->Expected_pdata_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_length)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterReadTRBBuild,CMockString_length);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_length, length, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_address)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterReadTRBBuild,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_address, address, cmock_line, CMockStringMismatch);
  }

  }
  if (cmock_call_instance->ReturnThruPtr_ptrb_Used)
  {
    memcpy(ptrb, cmock_call_instance->ReturnThruPtr_ptrb_Val,
      cmock_call_instance->ReturnThruPtr_ptrb_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_pdata_Used)
  {
    memcpy(pdata, cmock_call_instance->ReturnThruPtr_pdata_Val,
      cmock_call_instance->ReturnThruPtr_pdata_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_I2C_MasterReadTRBBuild(CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE* cmock_call_instance, I2C_TRANSACTION_REQUEST_BLOCK* ptrb, int ptrb_Depth, uint8_t* pdata, int pdata_Depth, uint8_t length, uint16_t address)
{
  cmock_call_instance->Expected_ptrb = ptrb;
  cmock_call_instance->Expected_ptrb_Depth = ptrb_Depth;
  cmock_call_instance->IgnoreArg_ptrb = 0;
  cmock_call_instance->ReturnThruPtr_ptrb_Used = 0;
  cmock_call_instance->Expected_pdata = pdata;
  cmock_call_instance->Expected_pdata_Depth = pdata_Depth;
  cmock_call_instance->IgnoreArg_pdata = 0;
  cmock_call_instance->ReturnThruPtr_pdata_Used = 0;
  cmock_call_instance->Expected_length = length;
  cmock_call_instance->IgnoreArg_length = 0;
  cmock_call_instance->Expected_address = address;
  cmock_call_instance->IgnoreArg_address = 0;
}

void I2C_MasterReadTRBBuild_CMockIgnore(void)
{
  Mock.I2C_MasterReadTRBBuild_IgnoreBool = (int)1;
}

void I2C_MasterReadTRBBuild_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE));
  CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterReadTRBBuild_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterReadTRBBuild_CallInstance, cmock_guts_index);
  Mock.I2C_MasterReadTRBBuild_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void I2C_MasterReadTRBBuild_CMockExpect(UNITY_LINE_TYPE cmock_line, I2C_TRANSACTION_REQUEST_BLOCK* ptrb, uint8_t* pdata, uint8_t length, uint16_t address)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE));
  CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterReadTRBBuild_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterReadTRBBuild_CallInstance, cmock_guts_index);
  Mock.I2C_MasterReadTRBBuild_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_I2C_MasterReadTRBBuild(cmock_call_instance, ptrb, 1, pdata, 1, length, address);
  UNITY_CLR_DETAILS();
}

void I2C_MasterReadTRBBuild_StubWithCallback(CMOCK_I2C_MasterReadTRBBuild_CALLBACK Callback)
{
  Mock.I2C_MasterReadTRBBuild_CallbackFunctionPointer = Callback;
}

void I2C_MasterReadTRBBuild_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, I2C_TRANSACTION_REQUEST_BLOCK* ptrb, int ptrb_Depth, uint8_t* pdata, int pdata_Depth, uint8_t length, uint16_t address)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE));
  CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterReadTRBBuild_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterReadTRBBuild_CallInstance, cmock_guts_index);
  Mock.I2C_MasterReadTRBBuild_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_I2C_MasterReadTRBBuild(cmock_call_instance, ptrb, ptrb_Depth, pdata, pdata_Depth, length, address);
}

void I2C_MasterReadTRBBuild_CMockReturnMemThruPtr_ptrb(UNITY_LINE_TYPE cmock_line, I2C_TRANSACTION_REQUEST_BLOCK* ptrb, int cmock_size)
{
  CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterReadTRBBuild_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_ptrb_Used = 1;
  cmock_call_instance->ReturnThruPtr_ptrb_Val = ptrb;
  cmock_call_instance->ReturnThruPtr_ptrb_Size = cmock_size;
}

void I2C_MasterReadTRBBuild_CMockReturnMemThruPtr_pdata(UNITY_LINE_TYPE cmock_line, uint8_t* pdata, int cmock_size)
{
  CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterReadTRBBuild_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_pdata_Used = 1;
  cmock_call_instance->ReturnThruPtr_pdata_Val = pdata;
  cmock_call_instance->ReturnThruPtr_pdata_Size = cmock_size;
}

void I2C_MasterReadTRBBuild_CMockIgnoreArg_ptrb(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterReadTRBBuild_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_ptrb = 1;
}

void I2C_MasterReadTRBBuild_CMockIgnoreArg_pdata(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterReadTRBBuild_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pdata = 1;
}

void I2C_MasterReadTRBBuild_CMockIgnoreArg_length(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterReadTRBBuild_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_length = 1;
}

void I2C_MasterReadTRBBuild_CMockIgnoreArg_address(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterReadTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterReadTRBBuild_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_address = 1;
}

void I2C_MasterWriteTRBBuild(I2C_TRANSACTION_REQUEST_BLOCK* ptrb, uint8_t* pdata, uint8_t length, uint16_t address)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_I2C_MasterWriteTRBBuild);
  CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C_MasterWriteTRBBuild_CallInstance);
  Mock.I2C_MasterWriteTRBBuild_CallInstance = CMock_Guts_MemNext(Mock.I2C_MasterWriteTRBBuild_CallInstance);
  if (Mock.I2C_MasterWriteTRBBuild_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.I2C_MasterWriteTRBBuild_CallbackFunctionPointer != NULL)
  {
    Mock.I2C_MasterWriteTRBBuild_CallbackFunctionPointer(ptrb, pdata, length, address, Mock.I2C_MasterWriteTRBBuild_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_ptrb)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterWriteTRBBuild,CMockString_ptrb);
    if (cmock_call_instance->Expected_ptrb == NULL)
      { UNITY_TEST_ASSERT_NULL(ptrb, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_ptrb), (void*)(ptrb), sizeof(I2C_TRANSACTION_REQUEST_BLOCK), cmock_call_instance->Expected_ptrb_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_pdata)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterWriteTRBBuild,CMockString_pdata);
    if (cmock_call_instance->Expected_pdata == NULL)
      { UNITY_TEST_ASSERT_NULL(pdata, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_pdata, pdata, cmock_call_instance->Expected_pdata_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_length)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterWriteTRBBuild,CMockString_length);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_length, length, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_address)
  {
    UNITY_SET_DETAILS(CMockString_I2C_MasterWriteTRBBuild,CMockString_address);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_address, address, cmock_line, CMockStringMismatch);
  }

  }
  if (cmock_call_instance->ReturnThruPtr_ptrb_Used)
  {
    memcpy(ptrb, cmock_call_instance->ReturnThruPtr_ptrb_Val,
      cmock_call_instance->ReturnThruPtr_ptrb_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_pdata_Used)
  {
    memcpy(pdata, cmock_call_instance->ReturnThruPtr_pdata_Val,
      cmock_call_instance->ReturnThruPtr_pdata_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_I2C_MasterWriteTRBBuild(CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE* cmock_call_instance, I2C_TRANSACTION_REQUEST_BLOCK* ptrb, int ptrb_Depth, uint8_t* pdata, int pdata_Depth, uint8_t length, uint16_t address)
{
  cmock_call_instance->Expected_ptrb = ptrb;
  cmock_call_instance->Expected_ptrb_Depth = ptrb_Depth;
  cmock_call_instance->IgnoreArg_ptrb = 0;
  cmock_call_instance->ReturnThruPtr_ptrb_Used = 0;
  cmock_call_instance->Expected_pdata = pdata;
  cmock_call_instance->Expected_pdata_Depth = pdata_Depth;
  cmock_call_instance->IgnoreArg_pdata = 0;
  cmock_call_instance->ReturnThruPtr_pdata_Used = 0;
  cmock_call_instance->Expected_length = length;
  cmock_call_instance->IgnoreArg_length = 0;
  cmock_call_instance->Expected_address = address;
  cmock_call_instance->IgnoreArg_address = 0;
}

void I2C_MasterWriteTRBBuild_CMockIgnore(void)
{
  Mock.I2C_MasterWriteTRBBuild_IgnoreBool = (int)1;
}

void I2C_MasterWriteTRBBuild_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE));
  CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterWriteTRBBuild_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterWriteTRBBuild_CallInstance, cmock_guts_index);
  Mock.I2C_MasterWriteTRBBuild_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void I2C_MasterWriteTRBBuild_CMockExpect(UNITY_LINE_TYPE cmock_line, I2C_TRANSACTION_REQUEST_BLOCK* ptrb, uint8_t* pdata, uint8_t length, uint16_t address)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE));
  CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterWriteTRBBuild_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterWriteTRBBuild_CallInstance, cmock_guts_index);
  Mock.I2C_MasterWriteTRBBuild_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_I2C_MasterWriteTRBBuild(cmock_call_instance, ptrb, 1, pdata, 1, length, address);
  UNITY_CLR_DETAILS();
}

void I2C_MasterWriteTRBBuild_StubWithCallback(CMOCK_I2C_MasterWriteTRBBuild_CALLBACK Callback)
{
  Mock.I2C_MasterWriteTRBBuild_CallbackFunctionPointer = Callback;
}

void I2C_MasterWriteTRBBuild_CMockExpectWithArray(UNITY_LINE_TYPE cmock_line, I2C_TRANSACTION_REQUEST_BLOCK* ptrb, int ptrb_Depth, uint8_t* pdata, int pdata_Depth, uint8_t length, uint16_t address)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE));
  CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterWriteTRBBuild_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterWriteTRBBuild_CallInstance, cmock_guts_index);
  Mock.I2C_MasterWriteTRBBuild_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_I2C_MasterWriteTRBBuild(cmock_call_instance, ptrb, ptrb_Depth, pdata, pdata_Depth, length, address);
}

void I2C_MasterWriteTRBBuild_CMockReturnMemThruPtr_ptrb(UNITY_LINE_TYPE cmock_line, I2C_TRANSACTION_REQUEST_BLOCK* ptrb, int cmock_size)
{
  CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterWriteTRBBuild_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_ptrb_Used = 1;
  cmock_call_instance->ReturnThruPtr_ptrb_Val = ptrb;
  cmock_call_instance->ReturnThruPtr_ptrb_Size = cmock_size;
}

void I2C_MasterWriteTRBBuild_CMockReturnMemThruPtr_pdata(UNITY_LINE_TYPE cmock_line, uint8_t* pdata, int cmock_size)
{
  CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterWriteTRBBuild_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_pdata_Used = 1;
  cmock_call_instance->ReturnThruPtr_pdata_Val = pdata;
  cmock_call_instance->ReturnThruPtr_pdata_Size = cmock_size;
}

void I2C_MasterWriteTRBBuild_CMockIgnoreArg_ptrb(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterWriteTRBBuild_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_ptrb = 1;
}

void I2C_MasterWriteTRBBuild_CMockIgnoreArg_pdata(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterWriteTRBBuild_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pdata = 1;
}

void I2C_MasterWriteTRBBuild_CMockIgnoreArg_length(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterWriteTRBBuild_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_length = 1;
}

void I2C_MasterWriteTRBBuild_CMockIgnoreArg_address(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterWriteTRBBuild_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.I2C_MasterWriteTRBBuild_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_address = 1;
}

_Bool I2C_MasterQueueIsEmpty(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_I2C_MasterQueueIsEmpty);
  CMOCK_I2C_MasterQueueIsEmpty_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterQueueIsEmpty_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C_MasterQueueIsEmpty_CallInstance);
  Mock.I2C_MasterQueueIsEmpty_CallInstance = CMock_Guts_MemNext(Mock.I2C_MasterQueueIsEmpty_CallInstance);
  if (Mock.I2C_MasterQueueIsEmpty_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.I2C_MasterQueueIsEmpty_FinalReturn;
    memcpy(&Mock.I2C_MasterQueueIsEmpty_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(_Bool));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.I2C_MasterQueueIsEmpty_CallbackFunctionPointer != NULL)
  {
    return Mock.I2C_MasterQueueIsEmpty_CallbackFunctionPointer(Mock.I2C_MasterQueueIsEmpty_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void I2C_MasterQueueIsEmpty_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterQueueIsEmpty_CALL_INSTANCE));
  CMOCK_I2C_MasterQueueIsEmpty_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterQueueIsEmpty_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterQueueIsEmpty_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterQueueIsEmpty_CallInstance, cmock_guts_index);
  Mock.I2C_MasterQueueIsEmpty_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.I2C_MasterQueueIsEmpty_IgnoreBool = (int)1;
}

void I2C_MasterQueueIsEmpty_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterQueueIsEmpty_CALL_INSTANCE));
  CMOCK_I2C_MasterQueueIsEmpty_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterQueueIsEmpty_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterQueueIsEmpty_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterQueueIsEmpty_CallInstance, cmock_guts_index);
  Mock.I2C_MasterQueueIsEmpty_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void I2C_MasterQueueIsEmpty_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterQueueIsEmpty_CALL_INSTANCE));
  CMOCK_I2C_MasterQueueIsEmpty_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterQueueIsEmpty_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterQueueIsEmpty_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterQueueIsEmpty_CallInstance, cmock_guts_index);
  Mock.I2C_MasterQueueIsEmpty_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(_Bool));
  UNITY_CLR_DETAILS();
}

void I2C_MasterQueueIsEmpty_StubWithCallback(CMOCK_I2C_MasterQueueIsEmpty_CALLBACK Callback)
{
  Mock.I2C_MasterQueueIsEmpty_CallbackFunctionPointer = Callback;
}

_Bool I2C_MasterQueueIsFull(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_I2C_MasterQueueIsFull);
  CMOCK_I2C_MasterQueueIsFull_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterQueueIsFull_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C_MasterQueueIsFull_CallInstance);
  Mock.I2C_MasterQueueIsFull_CallInstance = CMock_Guts_MemNext(Mock.I2C_MasterQueueIsFull_CallInstance);
  if (Mock.I2C_MasterQueueIsFull_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.I2C_MasterQueueIsFull_FinalReturn;
    memcpy(&Mock.I2C_MasterQueueIsFull_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(_Bool));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.I2C_MasterQueueIsFull_CallbackFunctionPointer != NULL)
  {
    return Mock.I2C_MasterQueueIsFull_CallbackFunctionPointer(Mock.I2C_MasterQueueIsFull_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void I2C_MasterQueueIsFull_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterQueueIsFull_CALL_INSTANCE));
  CMOCK_I2C_MasterQueueIsFull_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterQueueIsFull_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterQueueIsFull_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterQueueIsFull_CallInstance, cmock_guts_index);
  Mock.I2C_MasterQueueIsFull_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.I2C_MasterQueueIsFull_IgnoreBool = (int)1;
}

void I2C_MasterQueueIsFull_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterQueueIsFull_CALL_INSTANCE));
  CMOCK_I2C_MasterQueueIsFull_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterQueueIsFull_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterQueueIsFull_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterQueueIsFull_CallInstance, cmock_guts_index);
  Mock.I2C_MasterQueueIsFull_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void I2C_MasterQueueIsFull_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_MasterQueueIsFull_CALL_INSTANCE));
  CMOCK_I2C_MasterQueueIsFull_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_MasterQueueIsFull_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_MasterQueueIsFull_CallInstance = CMock_Guts_MemChain(Mock.I2C_MasterQueueIsFull_CallInstance, cmock_guts_index);
  Mock.I2C_MasterQueueIsFull_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(_Bool));
  UNITY_CLR_DETAILS();
}

void I2C_MasterQueueIsFull_StubWithCallback(CMOCK_I2C_MasterQueueIsFull_CALLBACK Callback)
{
  Mock.I2C_MasterQueueIsFull_CallbackFunctionPointer = Callback;
}

void I2C_BusCollisionISR(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_I2C_BusCollisionISR);
  CMOCK_I2C_BusCollisionISR_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_BusCollisionISR_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C_BusCollisionISR_CallInstance);
  Mock.I2C_BusCollisionISR_CallInstance = CMock_Guts_MemNext(Mock.I2C_BusCollisionISR_CallInstance);
  if (Mock.I2C_BusCollisionISR_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.I2C_BusCollisionISR_CallbackFunctionPointer != NULL)
  {
    Mock.I2C_BusCollisionISR_CallbackFunctionPointer(Mock.I2C_BusCollisionISR_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  UNITY_CLR_DETAILS();
}

void I2C_BusCollisionISR_CMockIgnore(void)
{
  Mock.I2C_BusCollisionISR_IgnoreBool = (int)1;
}

void I2C_BusCollisionISR_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_BusCollisionISR_CALL_INSTANCE));
  CMOCK_I2C_BusCollisionISR_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_BusCollisionISR_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_BusCollisionISR_CallInstance = CMock_Guts_MemChain(Mock.I2C_BusCollisionISR_CallInstance, cmock_guts_index);
  Mock.I2C_BusCollisionISR_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void I2C_BusCollisionISR_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_BusCollisionISR_CALL_INSTANCE));
  CMOCK_I2C_BusCollisionISR_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_BusCollisionISR_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_BusCollisionISR_CallInstance = CMock_Guts_MemChain(Mock.I2C_BusCollisionISR_CallInstance, cmock_guts_index);
  Mock.I2C_BusCollisionISR_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  UNITY_CLR_DETAILS();
}

void I2C_BusCollisionISR_StubWithCallback(CMOCK_I2C_BusCollisionISR_CALLBACK Callback)
{
  Mock.I2C_BusCollisionISR_CallbackFunctionPointer = Callback;
}

void I2C_ISR(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_I2C_ISR);
  CMOCK_I2C_ISR_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_ISR_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.I2C_ISR_CallInstance);
  Mock.I2C_ISR_CallInstance = CMock_Guts_MemNext(Mock.I2C_ISR_CallInstance);
  if (Mock.I2C_ISR_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.I2C_ISR_CallbackFunctionPointer != NULL)
  {
    Mock.I2C_ISR_CallbackFunctionPointer(Mock.I2C_ISR_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  UNITY_CLR_DETAILS();
}

void I2C_ISR_CMockIgnore(void)
{
  Mock.I2C_ISR_IgnoreBool = (int)1;
}

void I2C_ISR_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_ISR_CALL_INSTANCE));
  CMOCK_I2C_ISR_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_ISR_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_ISR_CallInstance = CMock_Guts_MemChain(Mock.I2C_ISR_CallInstance, cmock_guts_index);
  Mock.I2C_ISR_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void I2C_ISR_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_I2C_ISR_CALL_INSTANCE));
  CMOCK_I2C_ISR_CALL_INSTANCE* cmock_call_instance = (CMOCK_I2C_ISR_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.I2C_ISR_CallInstance = CMock_Guts_MemChain(Mock.I2C_ISR_CallInstance, cmock_guts_index);
  Mock.I2C_ISR_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  UNITY_CLR_DETAILS();
}

void I2C_ISR_StubWithCallback(CMOCK_I2C_ISR_CALLBACK Callback)
{
  Mock.I2C_ISR_CallbackFunctionPointer = Callback;
}

