/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKPIN_MANAGER_H
#define _MOCKPIN_MANAGER_H

#include "pin_manager.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockpin_manager_Init(void);
void Mockpin_manager_Destroy(void);
void Mockpin_manager_Verify(void);


typedef void(*cmock_pin_manager_func_ptr1)(void);
typedef void(*cmock_pin_manager_func_ptr2)(void);


#define PIN_MANAGER_Initialize_Ignore() PIN_MANAGER_Initialize_CMockIgnore()
void PIN_MANAGER_Initialize_CMockIgnore(void);
#define PIN_MANAGER_Initialize_ExpectAnyArgs() PIN_MANAGER_Initialize_CMockExpectAnyArgs(__LINE__)
void PIN_MANAGER_Initialize_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define PIN_MANAGER_Initialize_Expect() PIN_MANAGER_Initialize_CMockExpect(__LINE__)
void PIN_MANAGER_Initialize_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_PIN_MANAGER_Initialize_CALLBACK)(int cmock_num_calls);
void PIN_MANAGER_Initialize_StubWithCallback(CMOCK_PIN_MANAGER_Initialize_CALLBACK Callback);
#define PIN_MANAGER_IOC_Ignore() PIN_MANAGER_IOC_CMockIgnore()
void PIN_MANAGER_IOC_CMockIgnore(void);
#define PIN_MANAGER_IOC_ExpectAnyArgs() PIN_MANAGER_IOC_CMockExpectAnyArgs(__LINE__)
void PIN_MANAGER_IOC_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define PIN_MANAGER_IOC_Expect() PIN_MANAGER_IOC_CMockExpect(__LINE__)
void PIN_MANAGER_IOC_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_PIN_MANAGER_IOC_CALLBACK)(int cmock_num_calls);
void PIN_MANAGER_IOC_StubWithCallback(CMOCK_PIN_MANAGER_IOC_CALLBACK Callback);
#define IOCAF4_ISR_Ignore() IOCAF4_ISR_CMockIgnore()
void IOCAF4_ISR_CMockIgnore(void);
#define IOCAF4_ISR_ExpectAnyArgs() IOCAF4_ISR_CMockExpectAnyArgs(__LINE__)
void IOCAF4_ISR_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define IOCAF4_ISR_Expect() IOCAF4_ISR_CMockExpect(__LINE__)
void IOCAF4_ISR_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_IOCAF4_ISR_CALLBACK)(int cmock_num_calls);
void IOCAF4_ISR_StubWithCallback(CMOCK_IOCAF4_ISR_CALLBACK Callback);
#define IOCAF4_SetInterruptHandler_Ignore() IOCAF4_SetInterruptHandler_CMockIgnore()
void IOCAF4_SetInterruptHandler_CMockIgnore(void);
#define IOCAF4_SetInterruptHandler_ExpectAnyArgs() IOCAF4_SetInterruptHandler_CMockExpectAnyArgs(__LINE__)
void IOCAF4_SetInterruptHandler_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define IOCAF4_SetInterruptHandler_Expect(InterruptHandler) IOCAF4_SetInterruptHandler_CMockExpect(__LINE__, InterruptHandler)
void IOCAF4_SetInterruptHandler_CMockExpect(UNITY_LINE_TYPE cmock_line, cmock_pin_manager_func_ptr1 InterruptHandler);
typedef void (* CMOCK_IOCAF4_SetInterruptHandler_CALLBACK)(cmock_pin_manager_func_ptr1 InterruptHandler, int cmock_num_calls);
void IOCAF4_SetInterruptHandler_StubWithCallback(CMOCK_IOCAF4_SetInterruptHandler_CALLBACK Callback);
#define IOCAF4_SetInterruptHandler_IgnoreArg_InterruptHandler() IOCAF4_SetInterruptHandler_CMockIgnoreArg_InterruptHandler(__LINE__)
void IOCAF4_SetInterruptHandler_CMockIgnoreArg_InterruptHandler(UNITY_LINE_TYPE cmock_line);
#define IOCAF4_DefaultInterruptHandler_Ignore() IOCAF4_DefaultInterruptHandler_CMockIgnore()
void IOCAF4_DefaultInterruptHandler_CMockIgnore(void);
#define IOCAF4_DefaultInterruptHandler_ExpectAnyArgs() IOCAF4_DefaultInterruptHandler_CMockExpectAnyArgs(__LINE__)
void IOCAF4_DefaultInterruptHandler_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define IOCAF4_DefaultInterruptHandler_Expect() IOCAF4_DefaultInterruptHandler_CMockExpect(__LINE__)
void IOCAF4_DefaultInterruptHandler_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_IOCAF4_DefaultInterruptHandler_CALLBACK)(int cmock_num_calls);
void IOCAF4_DefaultInterruptHandler_StubWithCallback(CMOCK_IOCAF4_DefaultInterruptHandler_CALLBACK Callback);
#define IOCAF5_ISR_Ignore() IOCAF5_ISR_CMockIgnore()
void IOCAF5_ISR_CMockIgnore(void);
#define IOCAF5_ISR_ExpectAnyArgs() IOCAF5_ISR_CMockExpectAnyArgs(__LINE__)
void IOCAF5_ISR_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define IOCAF5_ISR_Expect() IOCAF5_ISR_CMockExpect(__LINE__)
void IOCAF5_ISR_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_IOCAF5_ISR_CALLBACK)(int cmock_num_calls);
void IOCAF5_ISR_StubWithCallback(CMOCK_IOCAF5_ISR_CALLBACK Callback);
#define IOCAF5_SetInterruptHandler_Ignore() IOCAF5_SetInterruptHandler_CMockIgnore()
void IOCAF5_SetInterruptHandler_CMockIgnore(void);
#define IOCAF5_SetInterruptHandler_ExpectAnyArgs() IOCAF5_SetInterruptHandler_CMockExpectAnyArgs(__LINE__)
void IOCAF5_SetInterruptHandler_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define IOCAF5_SetInterruptHandler_Expect(InterruptHandler) IOCAF5_SetInterruptHandler_CMockExpect(__LINE__, InterruptHandler)
void IOCAF5_SetInterruptHandler_CMockExpect(UNITY_LINE_TYPE cmock_line, cmock_pin_manager_func_ptr2 InterruptHandler);
typedef void (* CMOCK_IOCAF5_SetInterruptHandler_CALLBACK)(cmock_pin_manager_func_ptr2 InterruptHandler, int cmock_num_calls);
void IOCAF5_SetInterruptHandler_StubWithCallback(CMOCK_IOCAF5_SetInterruptHandler_CALLBACK Callback);
#define IOCAF5_SetInterruptHandler_IgnoreArg_InterruptHandler() IOCAF5_SetInterruptHandler_CMockIgnoreArg_InterruptHandler(__LINE__)
void IOCAF5_SetInterruptHandler_CMockIgnoreArg_InterruptHandler(UNITY_LINE_TYPE cmock_line);
#define IOCAF5_DefaultInterruptHandler_Ignore() IOCAF5_DefaultInterruptHandler_CMockIgnore()
void IOCAF5_DefaultInterruptHandler_CMockIgnore(void);
#define IOCAF5_DefaultInterruptHandler_ExpectAnyArgs() IOCAF5_DefaultInterruptHandler_CMockExpectAnyArgs(__LINE__)
void IOCAF5_DefaultInterruptHandler_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define IOCAF5_DefaultInterruptHandler_Expect() IOCAF5_DefaultInterruptHandler_CMockExpect(__LINE__)
void IOCAF5_DefaultInterruptHandler_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_IOCAF5_DefaultInterruptHandler_CALLBACK)(int cmock_num_calls);
void IOCAF5_DefaultInterruptHandler_StubWithCallback(CMOCK_IOCAF5_DefaultInterruptHandler_CALLBACK Callback);

#endif
