/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockPressure_Part2.h"

static const char* CMockString_TryToGetSingleVacuumMeasurement = "TryToGetSingleVacuumMeasurement";
static const char* CMockString_pDiff = "pDiff";
static const char* CMockString_pExternal = "pExternal";
static const char* CMockString_pInternal = "pInternal";

typedef struct _CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  ErrorCode_t ReturnVal;
  int CallOrder;
  uint16_t* Expected_pInternal;
  uint16_t* Expected_pExternal;
  uint16_t* Expected_pDiff;
  int Expected_pInternal_Depth;
  int Expected_pExternal_Depth;
  int Expected_pDiff_Depth;
  int ReturnThruPtr_pInternal_Used;
  uint16_t* ReturnThruPtr_pInternal_Val;
  int ReturnThruPtr_pInternal_Size;
  int ReturnThruPtr_pExternal_Used;
  uint16_t* ReturnThruPtr_pExternal_Val;
  int ReturnThruPtr_pExternal_Size;
  int ReturnThruPtr_pDiff_Used;
  uint16_t* ReturnThruPtr_pDiff_Val;
  int ReturnThruPtr_pDiff_Size;
  int IgnoreArg_pInternal;
  int IgnoreArg_pExternal;
  int IgnoreArg_pDiff;

} CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE;

static struct MockPressure_Part2Instance
{
  int TryToGetSingleVacuumMeasurement_IgnoreBool;
  ErrorCode_t TryToGetSingleVacuumMeasurement_FinalReturn;
  CMOCK_TryToGetSingleVacuumMeasurement_CALLBACK TryToGetSingleVacuumMeasurement_CallbackFunctionPointer;
  int TryToGetSingleVacuumMeasurement_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE TryToGetSingleVacuumMeasurement_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void MockPressure_Part2_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.TryToGetSingleVacuumMeasurement_IgnoreBool)
    Mock.TryToGetSingleVacuumMeasurement_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_TryToGetSingleVacuumMeasurement);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.TryToGetSingleVacuumMeasurement_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.TryToGetSingleVacuumMeasurement_CallbackFunctionPointer != NULL)
    Mock.TryToGetSingleVacuumMeasurement_CallInstance = CMOCK_GUTS_NONE;
}

void MockPressure_Part2_Init(void)
{
  MockPressure_Part2_Destroy();
}

void MockPressure_Part2_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.TryToGetSingleVacuumMeasurement_CallbackFunctionPointer = NULL;
  Mock.TryToGetSingleVacuumMeasurement_CallbackCalls = 0;
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

ErrorCode_t TryToGetSingleVacuumMeasurement(uint16_t* pInternal, uint16_t* pExternal, uint16_t* pDiff)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_TryToGetSingleVacuumMeasurement);
  CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE* cmock_call_instance = (CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TryToGetSingleVacuumMeasurement_CallInstance);
  Mock.TryToGetSingleVacuumMeasurement_CallInstance = CMock_Guts_MemNext(Mock.TryToGetSingleVacuumMeasurement_CallInstance);
  if (Mock.TryToGetSingleVacuumMeasurement_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.TryToGetSingleVacuumMeasurement_FinalReturn;
    memcpy(&Mock.TryToGetSingleVacuumMeasurement_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(ErrorCode_t));
    return cmock_call_instance->ReturnVal;
  }
  if (Mock.TryToGetSingleVacuumMeasurement_CallbackFunctionPointer != NULL)
  {
    return Mock.TryToGetSingleVacuumMeasurement_CallbackFunctionPointer(pInternal, pExternal, pDiff, Mock.TryToGetSingleVacuumMeasurement_CallbackCalls++);
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_pInternal)
  {
    UNITY_SET_DETAILS(CMockString_TryToGetSingleVacuumMeasurement,CMockString_pInternal);
    if (cmock_call_instance->Expected_pInternal == NULL)
      { UNITY_TEST_ASSERT_NULL(pInternal, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX16_ARRAY(cmock_call_instance->Expected_pInternal, pInternal, cmock_call_instance->Expected_pInternal_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_pExternal)
  {
    UNITY_SET_DETAILS(CMockString_TryToGetSingleVacuumMeasurement,CMockString_pExternal);
    if (cmock_call_instance->Expected_pExternal == NULL)
      { UNITY_TEST_ASSERT_NULL(pExternal, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX16_ARRAY(cmock_call_instance->Expected_pExternal, pExternal, cmock_call_instance->Expected_pExternal_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_pDiff)
  {
    UNITY_SET_DETAILS(CMockString_TryToGetSingleVacuumMeasurement,CMockString_pDiff);
    if (cmock_call_instance->Expected_pDiff == NULL)
      { UNITY_TEST_ASSERT_NULL(pDiff, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX16_ARRAY(cmock_call_instance->Expected_pDiff, pDiff, cmock_call_instance->Expected_pDiff_Depth, cmock_line, CMockStringMismatch); }
  }

  }
  if (cmock_call_instance->ReturnThruPtr_pInternal_Used)
  {
    memcpy(pInternal, cmock_call_instance->ReturnThruPtr_pInternal_Val,
      cmock_call_instance->ReturnThruPtr_pInternal_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_pExternal_Used)
  {
    memcpy(pExternal, cmock_call_instance->ReturnThruPtr_pExternal_Val,
      cmock_call_instance->ReturnThruPtr_pExternal_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_pDiff_Used)
  {
    memcpy(pDiff, cmock_call_instance->ReturnThruPtr_pDiff_Val,
      cmock_call_instance->ReturnThruPtr_pDiff_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_TryToGetSingleVacuumMeasurement(CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE* cmock_call_instance, uint16_t* pInternal, int pInternal_Depth, uint16_t* pExternal, int pExternal_Depth, uint16_t* pDiff, int pDiff_Depth)
{
  cmock_call_instance->Expected_pInternal = pInternal;
  cmock_call_instance->Expected_pInternal_Depth = pInternal_Depth;
  cmock_call_instance->IgnoreArg_pInternal = 0;
  cmock_call_instance->ReturnThruPtr_pInternal_Used = 0;
  cmock_call_instance->Expected_pExternal = pExternal;
  cmock_call_instance->Expected_pExternal_Depth = pExternal_Depth;
  cmock_call_instance->IgnoreArg_pExternal = 0;
  cmock_call_instance->ReturnThruPtr_pExternal_Used = 0;
  cmock_call_instance->Expected_pDiff = pDiff;
  cmock_call_instance->Expected_pDiff_Depth = pDiff_Depth;
  cmock_call_instance->IgnoreArg_pDiff = 0;
  cmock_call_instance->ReturnThruPtr_pDiff_Used = 0;
}

void TryToGetSingleVacuumMeasurement_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE));
  CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE* cmock_call_instance = (CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TryToGetSingleVacuumMeasurement_CallInstance = CMock_Guts_MemChain(Mock.TryToGetSingleVacuumMeasurement_CallInstance, cmock_guts_index);
  Mock.TryToGetSingleVacuumMeasurement_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.TryToGetSingleVacuumMeasurement_IgnoreBool = (int)1;
}

void TryToGetSingleVacuumMeasurement_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE));
  CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE* cmock_call_instance = (CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TryToGetSingleVacuumMeasurement_CallInstance = CMock_Guts_MemChain(Mock.TryToGetSingleVacuumMeasurement_CallInstance, cmock_guts_index);
  Mock.TryToGetSingleVacuumMeasurement_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void TryToGetSingleVacuumMeasurement_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t* pInternal, uint16_t* pExternal, uint16_t* pDiff, ErrorCode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE));
  CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE* cmock_call_instance = (CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TryToGetSingleVacuumMeasurement_CallInstance = CMock_Guts_MemChain(Mock.TryToGetSingleVacuumMeasurement_CallInstance, cmock_guts_index);
  Mock.TryToGetSingleVacuumMeasurement_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_TryToGetSingleVacuumMeasurement(cmock_call_instance, pInternal, 1, pExternal, 1, pDiff, 1);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(ErrorCode_t));
  UNITY_CLR_DETAILS();
}

void TryToGetSingleVacuumMeasurement_StubWithCallback(CMOCK_TryToGetSingleVacuumMeasurement_CALLBACK Callback)
{
  Mock.TryToGetSingleVacuumMeasurement_CallbackFunctionPointer = Callback;
}

void TryToGetSingleVacuumMeasurement_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t* pInternal, int pInternal_Depth, uint16_t* pExternal, int pExternal_Depth, uint16_t* pDiff, int pDiff_Depth, ErrorCode_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE));
  CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE* cmock_call_instance = (CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TryToGetSingleVacuumMeasurement_CallInstance = CMock_Guts_MemChain(Mock.TryToGetSingleVacuumMeasurement_CallInstance, cmock_guts_index);
  Mock.TryToGetSingleVacuumMeasurement_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_TryToGetSingleVacuumMeasurement(cmock_call_instance, pInternal, pInternal_Depth, pExternal, pExternal_Depth, pDiff, pDiff_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void TryToGetSingleVacuumMeasurement_CMockReturnMemThruPtr_pInternal(UNITY_LINE_TYPE cmock_line, uint16_t* pInternal, int cmock_size)
{
  CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE* cmock_call_instance = (CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.TryToGetSingleVacuumMeasurement_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_pInternal_Used = 1;
  cmock_call_instance->ReturnThruPtr_pInternal_Val = pInternal;
  cmock_call_instance->ReturnThruPtr_pInternal_Size = cmock_size;
}

void TryToGetSingleVacuumMeasurement_CMockReturnMemThruPtr_pExternal(UNITY_LINE_TYPE cmock_line, uint16_t* pExternal, int cmock_size)
{
  CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE* cmock_call_instance = (CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.TryToGetSingleVacuumMeasurement_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_pExternal_Used = 1;
  cmock_call_instance->ReturnThruPtr_pExternal_Val = pExternal;
  cmock_call_instance->ReturnThruPtr_pExternal_Size = cmock_size;
}

void TryToGetSingleVacuumMeasurement_CMockReturnMemThruPtr_pDiff(UNITY_LINE_TYPE cmock_line, uint16_t* pDiff, int cmock_size)
{
  CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE* cmock_call_instance = (CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.TryToGetSingleVacuumMeasurement_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_pDiff_Used = 1;
  cmock_call_instance->ReturnThruPtr_pDiff_Val = pDiff;
  cmock_call_instance->ReturnThruPtr_pDiff_Size = cmock_size;
}

void TryToGetSingleVacuumMeasurement_CMockIgnoreArg_pInternal(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE* cmock_call_instance = (CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.TryToGetSingleVacuumMeasurement_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pInternal = 1;
}

void TryToGetSingleVacuumMeasurement_CMockIgnoreArg_pExternal(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE* cmock_call_instance = (CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.TryToGetSingleVacuumMeasurement_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pExternal = 1;
}

void TryToGetSingleVacuumMeasurement_CMockIgnoreArg_pDiff(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE* cmock_call_instance = (CMOCK_TryToGetSingleVacuumMeasurement_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.TryToGetSingleVacuumMeasurement_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pDiff = 1;
}

