/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSTATEMACHINECOMMON_H
#define _MOCKSTATEMACHINECOMMON_H

#include "StateMachineCommon.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockStateMachineCommon_Init(void);
void MockStateMachineCommon_Destroy(void);
void MockStateMachineCommon_Verify(void);





#endif
