format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_driver_glcd}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: DisplayHeight}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Menu
    attributes: {id: DisplaySettingsMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: DisplayWidth}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: DoubleBuffer}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: FrameBufferColorMode}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: KeyValueSet
    attributes: {id: FrameBufferMemoryMode}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Comment
    attributes: {id: HALComment}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: HALConnected}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_hal, value: 'true'}
  - type: String
    attributes: {id: Layer0Buffer0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0xA8000000'}
  - type: String
    attributes: {id: Layer0Buffer1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0xA8084D00'}
  - type: String
    attributes: {id: Layer1Buffer0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0xA8213400'}
  - type: String
    attributes: {id: Layer1Buffer1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0xA818E700'}
  - type: Boolean
    attributes: {id: Layer1Enable}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: String
    attributes: {id: Layer2Buffer0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0xA8109A00'}
  - type: String
    attributes: {id: Layer2Buffer1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0xA8084D00'}
  - type: Boolean
    attributes: {id: Layer2Enable}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: MasterClockSourceValue}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_driver_glcd, value: '200000000'}
  - type: Boolean
    attributes: {id: PaletteMode}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: PixelClock}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_driver_glcd, value: '10000000'}
  - type: Integer
    attributes: {id: PixelClockDivider}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '20'}
  - type: Integer
    attributes: {id: TotalNumLayers}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_driver_glcd, value: '1'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: gfx_driver_glcd}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_hal}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_display_driver}
- type: ElementPosition
  attributes: {x: '349', y: '18', id: gfx_driver_glcd}
