format_version: v1.0
type: UniqueComponent
attributes: {id: gfx_hal}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: AlphaBlendingEnable}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: BoundsClippingEnable}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: ColorConversionEnable}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: ColorMaskingEnable}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Combo
    attributes: {id: ColorModeHint}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: GFX_COLOR_MODE_RGB_565}
  - type: Boolean
    attributes: {id: DisableGlobalPaletteModeHint}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: aria_gfx_library, value: 'true'}
  - type: Boolean
    attributes: {id: DisplayChipSelectPolarity}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: DisplayDataEnable}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: DisplayDataEnablePolarity}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: DisplayDataWidth}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '16'}
  - type: Boolean
    attributes: {id: DisplayHSYNCNegative}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: DisplayHeight}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '800'}
  - type: Integer
    attributes: {id: DisplayHorzBackPorch}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '70'}
  - type: Integer
    attributes: {id: DisplayHorzFrontPorch}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '70'}
  - type: Menu
    attributes: {id: DisplayHorzMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: DisplayHorzPulseWidth}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '20'}
  - type: Boolean
    attributes: {id: DisplayInvLeftShift}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: DisplayMirroringEnable}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: DisplayName}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Custom Display}
  - type: Combo
    attributes: {id: DisplayOrientation}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Boolean
    attributes: {id: DisplayOrientationEnable}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: DisplayResetPolarity}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: DisplayUseChipSelect}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: DisplayUseReset}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: DisplayVSYNCNegative}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: DisplayVertBackPorch}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '13'}
  - type: Integer
    attributes: {id: DisplayVertFrontPorch}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Menu
    attributes: {id: DisplayVertMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Integer
    attributes: {id: DisplayVertPulseWidth}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '20'}
  - type: Integer
    attributes: {id: DisplayWidth}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '340'}
  - type: Boolean
    attributes: {id: DoubleBufferHint}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: DrawPipelineEnable}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: DriverInfoFunction}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_hal, value: driverGLCDInfoGet}
  - type: String
    attributes: {id: DriverInitFunction}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_hal, value: driverGLCDContextInitialize}
  - type: Menu
    attributes: {id: GFXRTOSMenu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: GFX_SYS_RTOS_TASK_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: GlobalPaletteModeHint}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: aria_gfx_library, value: 'false'}
  - type: Integer
    attributes: {id: HardwareLayerCountHint}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_driver_glcd, value: '1'}
  - type: Boolean
    attributes: {id: LCCRefreshHint}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: LayerClippingEnable}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: PixelClock}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_hal, value: '10000000'}
  - type: Integer
    attributes: {id: PixelClockHint}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_driver_glcd, value: '10000000'}
  - type: String
    attributes: {id: ProcInfoFunction}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_hal, value: procNANO2DInfoGet}
  - type: String
    attributes: {id: ProcInitFunction}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_hal, value: procNANO2DContextInitialize}
  - type: Integer
    attributes: {id: RefreshRate}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: gfx_hal, value: '23'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: gfx_display_driver}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_driver_glcd}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_driver_glcd}
  - type: DirectDependency
    attributes: {id: gfx_graphics_processor}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: gfx_driver_2dgpu}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_driver_2dgpu}
  - type: DirectCapability
    attributes: {id: gfx_hal}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: aria_gfx_library}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: gfx_hal}
- type: ElementPosition
  attributes: {x: '499', y: '21', id: gfx_hal}
