format_version: v1.0
type: UniqueComponent
attributes: {id: ocmp3}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: OCMP_CFGCON_OCACLK}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: KeyValueSet
    attributes: {id: OCMP_OCxCON_OCM}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
  - type: Boolean
    attributes: {id: OCMP_OCxCON_SIDL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Comment
    attributes: {id: OCMP_PERIOD_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Hex
    attributes: {id: OCxCON_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ocmp3, value: '8198'}
- type: ElementPosition
  attributes: {x: '869', y: '69', id: ocmp3}
