format_version: v1.0
type: UniqueComponent
attributes: {id: sys_time}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: SYS_TIME_MAX_TIMERS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '8'}
  - type: String
    attributes: {id: SYS_TIME_PLIB}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: sys_time, value: CORE_TIMER}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: sys_time_TMR_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: core_timer}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: CORE_TIMER_TMR}
- type: ElementPosition
  attributes: {x: '177', y: '134', id: sys_time}
