format_version: v1.0
type: UniqueComponent
attributes: {id: tmr9}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: TCON_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr9, value: '8304'}
  - type: Integer
    attributes: {id: TIMER_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr9, value: '390625'}
  - type: Long
    attributes: {id: TIMER_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr9, value: '389'}
  - type: KeyValueSet
    attributes: {id: TIMER_PRE_SCALER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: KeyValueSet
    attributes: {id: TIMER_SIDL}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Float
    attributes: {id: TIMER_TIME_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '167.7696'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1.0'}
  - type: Boolean
    attributes: {id: TMR_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr9, value: 'true'}
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: TMR_PRESCALER_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr9, value: '256'}
- type: ElementPosition
  attributes: {x: '870', y: '265', id: tmr9}
