/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  CMock_Init(); \
  UNITY_CLR_DETAILS(); \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
    CMock_Verify(); \
  } \
  CMock_Destroy(); \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include <setjmp.h>
#include <stdio.h>
#include "Mockadc.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_WhenCurrentStaysTheSameNoFrequencyAdjustment(void);
extern void test_OnDownwardSlopeWhenCurrentIsIncreasedThenDecreaseFrequency(void);
extern void test_WhenCurrentIsIncreasedOnIncreasedFrequencyThenKeepIncreasingFrequency(void);
extern void test_IfCurrentIsDecreasedInResponseToIncreasedFrequencyThenIncreaseFrequency(void);
extern void test_IfCurrentIsDecreasedInResponseToIncreasedFrequencyThenDecreaseFrequency(void);
extern void test_FrequencyOutOfRangeLowerBoundCheck(void);
extern void test_FrequencyOutOfRangeUpperBoundCheck(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  Mockadc_Init();
}
static void CMock_Verify(void)
{
  Mockadc_Verify();
}
static void CMock_Destroy(void)
{
  Mockadc_Destroy();
}

/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  CMock_Verify();
  CMock_Destroy();
  tearDown();
  CMock_Init();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_PowerTracker.c");
  RUN_TEST(test_WhenCurrentStaysTheSameNoFrequencyAdjustment, 56);
  RUN_TEST(test_OnDownwardSlopeWhenCurrentIsIncreasedThenDecreaseFrequency, 80);
  RUN_TEST(test_WhenCurrentIsIncreasedOnIncreasedFrequencyThenKeepIncreasingFrequency, 111);
  RUN_TEST(test_IfCurrentIsDecreasedInResponseToIncreasedFrequencyThenIncreaseFrequency, 139);
  RUN_TEST(test_IfCurrentIsDecreasedInResponseToIncreasedFrequencyThenDecreaseFrequency, 156);
  RUN_TEST(test_FrequencyOutOfRangeLowerBoundCheck, 179);
  RUN_TEST(test_FrequencyOutOfRangeUpperBoundCheck, 187);

  CMock_Guts_MemFreeFinal();
  return (UnityEnd());
}
