---
environment:
  logging:
    level: 20
    levels:
      framework.module: 10
    path: '.\logs'
    mode: 'w'

modules:
  digipot:
    #ftdi_url: 'ftdi://ftdi:232h:FT6YZF0N/1' # LeoTel B1 Rig
    ftdi_url: 'ftdi://ftdi:232h:FT717M0C/1'  # Occuity B1 Rig
    freq: 1000000.0
  nidaq:
    #device: 'PXI1Slot2' # LeoTel NI PXIe-6363
    device: 'Dev1' # Occuity NI USB-6363
    signal_channel: 'ao0'
    encoder_lines: 'port0/line0:3'
    di_lines: 'port0/line4:7'
    do_lines: 'port1/line0:3'
    timing_counter: 'ctr0'
    timing_source: 'ctr0InternalOutput'
  serial_debug:
    path: '.\logs'
    ports:
      dspic: 'COM5'
      dar: 'COM4'
      efh: 'COM7'
      p24: 'COM6'
    baudrate: 115200
    mode: 'w'
    bufsize: 16384
    timeout: 3.
  touch:
    aa_port: 0
    aa_addr: 0x1A
    aa_timeout_ms: 6
    int_timeout_ms: 10
    touch_request: [ 0xD0, 0x00 ]
    touch_responses:
      wakeup_touch:                 [ 0x06, 0x01, 0x01, 0x01, 0x01, 0x01, 0xAB]
      wakeup_touch_lift_start:      [ 0x00, 0x01, 0x01, 0x01, 0x01, 0x01, 0xAB]
      wakeup_touch_lift_end:        [ 0x00, 0x01, 0x01, 0x01, 0x01, 0x00, 0xAB]
      scan_button_touch:            [ 0x06, 0x0A, 0x17, 0xFA, 0x4E, 0x01, 0xAB]
      scan_button_touch_lift_start: [ 0x00, 0x0A, 0x17, 0xFA, 0x4E, 0x01, 0xAB]
      scan_button_touch_lift_end:   [ 0x00, 0x0A, 0x17, 0xFA, 0x4F, 0x00, 0xAB]
      settings_button:              [ 0x06, 0x0F, 0x2D, 0x42, 0x4E, 0x01, 0xAB]
      settings_button_lift_start:   [ 0x00, 0x0F, 0x2D, 0x42, 0x4E, 0x01, 0xAB]
      settings_button_lift_end:     [ 0x00, 0x0F, 0x2D, 0x42, 0x4E, 0x00, 0xAB]
      dev_settings:                 [ 0x06, 0x09, 0x25, 0x0A, 0x10, 0x01, 0xAB]
      dev_settings_lift_start:      [ 0x00, 0x09, 0x25, 0x0A, 0x10, 0x01, 0xAB]
      dev_settings_lift_end:        [ 0x00, 0x09, 0x25, 0x0A, 0x10, 0x00, 0xAB]
      cancel_settings:              [ 0x06, 0x10, 0x30, 0x2F, 0x27, 0x01, 0xAB]
      cancel_settings_lift_start:   [ 0x00, 0x10, 0x30, 0x2F, 0x27, 0x01, 0xAB]
      cancel_settings_lift_end:     [ 0x00, 0x10, 0x30, 0x2F, 0x27, 0x00, 0xAB]
      apply_settings:               [ 0x06, 0x04, 0x31, 0x95, 0x37, 0x01, 0xAB]
      apply_settings_lift_start:    [ 0x00, 0x04, 0x31, 0x95, 0x37, 0x01, 0xAB]
      apply_settings_lift_end:      [ 0x00, 0x04, 0x31, 0x95, 0x37, 0x00, 0xAB]
      auto_scan:                    [ 0x06, 0x05, 0x2A, 0x17, 0x18, 0x01, 0xAB]
      auto_scan_lift_start:         [ 0x00, 0x05, 0x2A, 0x17, 0x18, 0x01, 0xAB]
      auto_scan_lift_end:           [ 0x00, 0x05, 0x2A, 0x17, 0x18, 0x00, 0xAB]
      laser_check:                  [ 0x06, 0x10, 0x2A, 0x27, 0x12, 0x01, 0xAB]
      laser_check_lift_start:       [ 0x00, 0x10, 0x2A, 0x27, 0x12, 0x01, 0xAB]
      laser_check_lift_end:         [ 0x00, 0x10, 0x2A, 0x27, 0x12, 0x00, 0xAB]
      min_lcd_brightness:           [ 0x06, 0x08, 0x05, 0x0A, 0x39, 0x01, 0xAB]
      min_lcd_brightness_start:     [ 0x00, 0x08, 0x05, 0x0A, 0x39, 0x01, 0xAB]
      min_lcd_brightness_end:       [ 0x00, 0x08, 0x05, 0x0A, 0x39, 0x00, 0xAB]
      max_lcd_brightness:           [ 0x06, 0x11, 0x07, 0x59, 0x4A, 0x01, 0xAB]
      max_lcd_brightness_start:     [ 0x00, 0x11, 0x07, 0x59, 0x4A, 0x01, 0xAB]
      max_lcd_brightness_end:       [ 0x00, 0x11, 0x07, 0x59, 0x4A, 0x00, 0xAB]
      med_lcd_brightness:           [ 0x06, 0x0D, 0x07, 0x94, 0x54, 0x01, 0xAB]
      med_lcd_brightness_start:     [ 0x00, 0x0D, 0x07, 0x94, 0x54, 0x01, 0xAB]
      med_lcd_brightness_end:       [ 0x00, 0x0D, 0x07, 0x94, 0x54, 0x00, 0xAB]
      lcd_brightness_75:            [ 0x06, 0x10, 0x05, 0x49, 0x27, 0x01, 0xAB]
      lcd_brightness_75_lift_start: [ 0x00, 0x10, 0x05, 0x49, 0x27, 0x01, 0xAB]
      lcd_brightness_75_lift_end:   [ 0x00, 0x10, 0x05, 0x49, 0x27, 0x00, 0xAB]
      lcd_brightness_25:            [ 0x06, 0x09, 0x06, 0xCC, 0x41, 0x01, 0xAB]
      lcd_brightness_25_lift_start: [ 0x00, 0x09, 0x06, 0xCC, 0x41, 0x01, 0xAB]
      lcd_brightness_25_lift_end:   [ 0x00, 0x09, 0x06, 0xCC, 0x41, 0x00, 0xAB]


test:
  devices:
    ft232h_i2c:
      ftdi_url: 'ftdi://ftdi:232h:FT6YZF0N/1'
      addr: 0x1A
    ft232h_spi:
      ftdi_url: 'ftdi://ftdi:232h:FT717M0C/1'
...
