/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  CMock_Init(); \
  UNITY_CLR_DETAILS(); \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
    CMock_Verify(); \
  } \
  CMock_Destroy(); \
  UnityConcludeTest(); \
}

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include <setjmp.h>
#include <stdio.h>
#include "Mockadc.h"
#include "MockPowerControl.h"
#include "MockPerformanceLogger.h"
#include "MockTimer.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_BatteryOutOfRangeWhenVddIsOver3V6(void);
extern void test_BoostVoltageIsOutOfRangeWhenBoostVoltageIsAbove33V(void);
extern void test_BoostVoltageIsOutOfRangeWhenBoostVoltageIsBelow16V(void);
extern void test_BatteryEndOfLifeWhenVddIsBelow1V9AndInitBoostDemandBelow18V(void);
extern void test_ReduceInitBootstDemandWhenVddIsBelow2V2(void);
extern void test_ReduceInitBootstDemandDownTo18VWhenVddIsBelow2V2(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  Mockadc_Init();
  MockPowerControl_Init();
  MockPerformanceLogger_Init();
  MockTimer_Init();
}
static void CMock_Verify(void)
{
  Mockadc_Verify();
  MockPowerControl_Verify();
  MockPerformanceLogger_Verify();
  MockTimer_Verify();
}
static void CMock_Destroy(void)
{
  Mockadc_Destroy();
  MockPowerControl_Destroy();
  MockPerformanceLogger_Destroy();
  MockTimer_Destroy();
}

/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
  CMock_Verify();
  CMock_Destroy();
  tearDown();
  CMock_Init();
  setUp();
}


/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_Battery.c");
  RUN_TEST(test_BatteryOutOfRangeWhenVddIsOver3V6, 94);
  RUN_TEST(test_BoostVoltageIsOutOfRangeWhenBoostVoltageIsAbove33V, 108);
  RUN_TEST(test_BoostVoltageIsOutOfRangeWhenBoostVoltageIsBelow16V, 121);
  RUN_TEST(test_BatteryEndOfLifeWhenVddIsBelow1V9AndInitBoostDemandBelow18V, 134);
  RUN_TEST(test_ReduceInitBootstDemandWhenVddIsBelow2V2, 142);
  RUN_TEST(test_ReduceInitBootstDemandDownTo18VWhenVddIsBelow2V2, 160);

  CMock_Guts_MemFreeFinal();
  return (UnityEnd());
}
