/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKDUTYCYCLE_H
#define _MOCKDUTYCYCLE_H

#include "DutyCycle.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockDutyCycle_Init(void);
void MockDutyCycle_Destroy(void);
void MockDutyCycle_Verify(void);




#define DCHistoryReset_Ignore() DCHistoryReset_CMockIgnore()
void DCHistoryReset_CMockIgnore(void);
#define DCHistoryReset_ExpectAnyArgs() DCHistoryReset_CMockExpectAnyArgs(__LINE__)
void DCHistoryReset_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define DCHistoryReset_Expect() DCHistoryReset_CMockExpect(__LINE__)
void DCHistoryReset_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_DCHistoryReset_CALLBACK)(int cmock_num_calls);
void DCHistoryReset_StubWithCallback(CMOCK_DCHistoryReset_CALLBACK Callback);
#define DCCalculateAll_Ignore() DCCalculateAll_CMockIgnore()
void DCCalculateAll_CMockIgnore(void);
#define DCCalculateAll_ExpectAnyArgs() DCCalculateAll_CMockExpectAnyArgs(__LINE__)
void DCCalculateAll_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define DCCalculateAll_Expect() DCCalculateAll_CMockExpect(__LINE__)
void DCCalculateAll_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_DCCalculateAll_CALLBACK)(int cmock_num_calls);
void DCCalculateAll_StubWithCallback(CMOCK_DCCalculateAll_CALLBACK Callback);
#define DCPumpOnUpdate_Ignore() DCPumpOnUpdate_CMockIgnore()
void DCPumpOnUpdate_CMockIgnore(void);
#define DCPumpOnUpdate_ExpectAnyArgs() DCPumpOnUpdate_CMockExpectAnyArgs(__LINE__)
void DCPumpOnUpdate_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define DCPumpOnUpdate_Expect() DCPumpOnUpdate_CMockExpect(__LINE__)
void DCPumpOnUpdate_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_DCPumpOnUpdate_CALLBACK)(int cmock_num_calls);
void DCPumpOnUpdate_StubWithCallback(CMOCK_DCPumpOnUpdate_CALLBACK Callback);
#define DCPumpOffUpdate_Ignore() DCPumpOffUpdate_CMockIgnore()
void DCPumpOffUpdate_CMockIgnore(void);
#define DCPumpOffUpdate_ExpectAnyArgs() DCPumpOffUpdate_CMockExpectAnyArgs(__LINE__)
void DCPumpOffUpdate_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define DCPumpOffUpdate_Expect() DCPumpOffUpdate_CMockExpect(__LINE__)
void DCPumpOffUpdate_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_DCPumpOffUpdate_CALLBACK)(int cmock_num_calls);
void DCPumpOffUpdate_StubWithCallback(CMOCK_DCPumpOffUpdate_CALLBACK Callback);
#define DCVaccumOffsetUpdateGet_IgnoreAndReturn(cmock_retval) DCVaccumOffsetUpdateGet_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void DCVaccumOffsetUpdateGet_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define DCVaccumOffsetUpdateGet_ExpectAnyArgsAndReturn(cmock_retval) DCVaccumOffsetUpdateGet_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void DCVaccumOffsetUpdateGet_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define DCVaccumOffsetUpdateGet_ExpectAndReturn(cmock_retval) DCVaccumOffsetUpdateGet_CMockExpectAndReturn(__LINE__, cmock_retval)
void DCVaccumOffsetUpdateGet_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_DCVaccumOffsetUpdateGet_CALLBACK)(int cmock_num_calls);
void DCVaccumOffsetUpdateGet_StubWithCallback(CMOCK_DCVaccumOffsetUpdateGet_CALLBACK Callback);
#define DCLeakGet_IgnoreAndReturn(cmock_retval) DCLeakGet_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void DCLeakGet_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define DCLeakGet_ExpectAnyArgsAndReturn(cmock_retval) DCLeakGet_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void DCLeakGet_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
#define DCLeakGet_ExpectAndReturn(cmock_retval) DCLeakGet_CMockExpectAndReturn(__LINE__, cmock_retval)
void DCLeakGet_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t cmock_to_return);
typedef uint8_t (* CMOCK_DCLeakGet_CALLBACK)(int cmock_num_calls);
void DCLeakGet_StubWithCallback(CMOCK_DCLeakGet_CALLBACK Callback);

#endif
