/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKPUMPFREQUENCYTRACKER_H
#define _MOCKPUMPFREQUENCYTRACKER_H

#include "PumpFrequencyTracker.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockPumpFrequencyTracker_Init(void);
void MockPumpFrequencyTracker_Destroy(void);
void MockPumpFrequencyTracker_Verify(void);




#define PumpFrequencyTracker_Init_Ignore() PumpFrequencyTracker_Init_CMockIgnore()
void PumpFrequencyTracker_Init_CMockIgnore(void);
#define PumpFrequencyTracker_Init_ExpectAnyArgs() PumpFrequencyTracker_Init_CMockExpectAnyArgs(__LINE__)
void PumpFrequencyTracker_Init_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define PumpFrequencyTracker_Init_Expect() PumpFrequencyTracker_Init_CMockExpect(__LINE__)
void PumpFrequencyTracker_Init_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_PumpFrequencyTracker_Init_CALLBACK)(int cmock_num_calls);
void PumpFrequencyTracker_Init_StubWithCallback(CMOCK_PumpFrequencyTracker_Init_CALLBACK Callback);
#define PumpFrequencyTracker_Optimise_IgnoreAndReturn(cmock_retval) PumpFrequencyTracker_Optimise_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void PumpFrequencyTracker_Optimise_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
#define PumpFrequencyTracker_Optimise_ExpectAnyArgsAndReturn(cmock_retval) PumpFrequencyTracker_Optimise_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void PumpFrequencyTracker_Optimise_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
#define PumpFrequencyTracker_Optimise_ExpectAndReturn(cmock_retval) PumpFrequencyTracker_Optimise_CMockExpectAndReturn(__LINE__, cmock_retval)
void PumpFrequencyTracker_Optimise_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
typedef ErrorCode_t (* CMOCK_PumpFrequencyTracker_Optimise_CALLBACK)(int cmock_num_calls);
void PumpFrequencyTracker_Optimise_StubWithCallback(CMOCK_PumpFrequencyTracker_Optimise_CALLBACK Callback);

#endif
