/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKBATTERY_H
#define _MOCKBATTERY_H

#include "Battery.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockBattery_Init(void);
void MockBattery_Destroy(void);
void MockBattery_Verify(void);




#define Battery_CheckVoltageBounds_IgnoreAndReturn(cmock_retval) Battery_CheckVoltageBounds_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void Battery_CheckVoltageBounds_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
#define Battery_CheckVoltageBounds_ExpectAnyArgsAndReturn(cmock_retval) Battery_CheckVoltageBounds_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void Battery_CheckVoltageBounds_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
#define Battery_CheckVoltageBounds_ExpectAndReturn(cmock_retval) Battery_CheckVoltageBounds_CMockExpectAndReturn(__LINE__, cmock_retval)
void Battery_CheckVoltageBounds_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
typedef ErrorCode_t (* CMOCK_Battery_CheckVoltageBounds_CALLBACK)(int cmock_num_calls);
void Battery_CheckVoltageBounds_StubWithCallback(CMOCK_Battery_CheckVoltageBounds_CALLBACK Callback);

#endif
