/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSTATEMACHINEFAULT_H
#define _MOCKSTATEMACHINEFAULT_H

#include "StateMachineFault.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockStateMachineFault_Init(void);
void MockStateMachineFault_Destroy(void);
void MockStateMachineFault_Verify(void);




#define Fault_IgnoreAndReturn(cmock_retval) Fault_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void Fault_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
#define Fault_ExpectAnyArgsAndReturn(cmock_retval) Fault_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void Fault_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, ErrorCode_t cmock_to_return);
#define Fault_ExpectAndReturn(aCurrentStateOnEntry, nextState, cmock_retval) Fault_CMockExpectAndReturn(__LINE__, aCurrentStateOnEntry, nextState, cmock_retval)
void Fault_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool_t aCurrentStateOnEntry, State_t* nextState, ErrorCode_t cmock_to_return);
typedef ErrorCode_t (* CMOCK_Fault_CALLBACK)(bool_t aCurrentStateOnEntry, State_t* nextState, int cmock_num_calls);
void Fault_StubWithCallback(CMOCK_Fault_CALLBACK Callback);
#define Fault_ExpectWithArrayAndReturn(aCurrentStateOnEntry, nextState, nextState_Depth, cmock_retval) Fault_CMockExpectWithArrayAndReturn(__LINE__, aCurrentStateOnEntry, nextState, nextState_Depth, cmock_retval)
void Fault_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, bool_t aCurrentStateOnEntry, State_t* nextState, int nextState_Depth, ErrorCode_t cmock_to_return);
#define Fault_ReturnThruPtr_nextState(nextState) Fault_CMockReturnMemThruPtr_nextState(__LINE__, nextState, sizeof(*nextState))
#define Fault_ReturnArrayThruPtr_nextState(nextState, cmock_len) Fault_CMockReturnMemThruPtr_nextState(__LINE__, nextState, (int)(cmock_len * (int)sizeof(*nextState)))
#define Fault_ReturnMemThruPtr_nextState(nextState, cmock_size) Fault_CMockReturnMemThruPtr_nextState(__LINE__, nextState, cmock_size)
void Fault_CMockReturnMemThruPtr_nextState(UNITY_LINE_TYPE cmock_line, State_t* nextState, int cmock_size);
#define Fault_IgnoreArg_aCurrentStateOnEntry() Fault_CMockIgnoreArg_aCurrentStateOnEntry(__LINE__)
void Fault_CMockIgnoreArg_aCurrentStateOnEntry(UNITY_LINE_TYPE cmock_line);
#define Fault_IgnoreArg_nextState() Fault_CMockIgnoreArg_nextState(__LINE__)
void Fault_CMockIgnoreArg_nextState(UNITY_LINE_TYPE cmock_line);

#endif
