/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKADC_H
#define _MOCKADC_H

#include "adc.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockadc_Init(void);
void Mockadc_Destroy(void);
void Mockadc_Verify(void);




#define ADC_Initialize_Ignore() ADC_Initialize_CMockIgnore()
void ADC_Initialize_CMockIgnore(void);
#define ADC_Initialize_ExpectAnyArgs() ADC_Initialize_CMockExpectAnyArgs(__LINE__)
void ADC_Initialize_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define ADC_Initialize_Expect() ADC_Initialize_CMockExpect(__LINE__)
void ADC_Initialize_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_ADC_Initialize_CALLBACK)(int cmock_num_calls);
void ADC_Initialize_StubWithCallback(CMOCK_ADC_Initialize_CALLBACK Callback);
#define ADC_SelectChannel_Ignore() ADC_SelectChannel_CMockIgnore()
void ADC_SelectChannel_CMockIgnore(void);
#define ADC_SelectChannel_ExpectAnyArgs() ADC_SelectChannel_CMockExpectAnyArgs(__LINE__)
void ADC_SelectChannel_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define ADC_SelectChannel_Expect(channel) ADC_SelectChannel_CMockExpect(__LINE__, channel)
void ADC_SelectChannel_CMockExpect(UNITY_LINE_TYPE cmock_line, adc_channel_t channel);
typedef void (* CMOCK_ADC_SelectChannel_CALLBACK)(adc_channel_t channel, int cmock_num_calls);
void ADC_SelectChannel_StubWithCallback(CMOCK_ADC_SelectChannel_CALLBACK Callback);
#define ADC_SelectChannel_IgnoreArg_channel() ADC_SelectChannel_CMockIgnoreArg_channel(__LINE__)
void ADC_SelectChannel_CMockIgnoreArg_channel(UNITY_LINE_TYPE cmock_line);
#define ADC_StartConversion_Ignore() ADC_StartConversion_CMockIgnore()
void ADC_StartConversion_CMockIgnore(void);
#define ADC_StartConversion_ExpectAnyArgs() ADC_StartConversion_CMockExpectAnyArgs(__LINE__)
void ADC_StartConversion_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define ADC_StartConversion_Expect() ADC_StartConversion_CMockExpect(__LINE__)
void ADC_StartConversion_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_ADC_StartConversion_CALLBACK)(int cmock_num_calls);
void ADC_StartConversion_StubWithCallback(CMOCK_ADC_StartConversion_CALLBACK Callback);
#define ADC_IsConversionDone_IgnoreAndReturn(cmock_retval) ADC_IsConversionDone_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void ADC_IsConversionDone_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return);
#define ADC_IsConversionDone_ExpectAnyArgsAndReturn(cmock_retval) ADC_IsConversionDone_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void ADC_IsConversionDone_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return);
#define ADC_IsConversionDone_ExpectAndReturn(cmock_retval) ADC_IsConversionDone_CMockExpectAndReturn(__LINE__, cmock_retval)
void ADC_IsConversionDone_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return);
typedef _Bool (* CMOCK_ADC_IsConversionDone_CALLBACK)(int cmock_num_calls);
void ADC_IsConversionDone_StubWithCallback(CMOCK_ADC_IsConversionDone_CALLBACK Callback);
#define ADC_GetConversionResult_IgnoreAndReturn(cmock_retval) ADC_GetConversionResult_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void ADC_GetConversionResult_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, adc_result_t cmock_to_return);
#define ADC_GetConversionResult_ExpectAnyArgsAndReturn(cmock_retval) ADC_GetConversionResult_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void ADC_GetConversionResult_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, adc_result_t cmock_to_return);
#define ADC_GetConversionResult_ExpectAndReturn(cmock_retval) ADC_GetConversionResult_CMockExpectAndReturn(__LINE__, cmock_retval)
void ADC_GetConversionResult_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, adc_result_t cmock_to_return);
typedef adc_result_t (* CMOCK_ADC_GetConversionResult_CALLBACK)(int cmock_num_calls);
void ADC_GetConversionResult_StubWithCallback(CMOCK_ADC_GetConversionResult_CALLBACK Callback);
#define ADC_GetConversion_IgnoreAndReturn(cmock_retval) ADC_GetConversion_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void ADC_GetConversion_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, adc_result_t cmock_to_return);
#define ADC_GetConversion_ExpectAnyArgsAndReturn(cmock_retval) ADC_GetConversion_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void ADC_GetConversion_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, adc_result_t cmock_to_return);
#define ADC_GetConversion_ExpectAndReturn(channel, cmock_retval) ADC_GetConversion_CMockExpectAndReturn(__LINE__, channel, cmock_retval)
void ADC_GetConversion_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, adc_channel_t channel, adc_result_t cmock_to_return);
typedef adc_result_t (* CMOCK_ADC_GetConversion_CALLBACK)(adc_channel_t channel, int cmock_num_calls);
void ADC_GetConversion_StubWithCallback(CMOCK_ADC_GetConversion_CALLBACK Callback);
#define ADC_GetConversion_IgnoreArg_channel() ADC_GetConversion_CMockIgnoreArg_channel(__LINE__)
void ADC_GetConversion_CMockIgnoreArg_channel(UNITY_LINE_TYPE cmock_line);
#define ADC_TemperatureAcquisitionDelay_Ignore() ADC_TemperatureAcquisitionDelay_CMockIgnore()
void ADC_TemperatureAcquisitionDelay_CMockIgnore(void);
#define ADC_TemperatureAcquisitionDelay_ExpectAnyArgs() ADC_TemperatureAcquisitionDelay_CMockExpectAnyArgs(__LINE__)
void ADC_TemperatureAcquisitionDelay_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define ADC_TemperatureAcquisitionDelay_Expect() ADC_TemperatureAcquisitionDelay_CMockExpect(__LINE__)
void ADC_TemperatureAcquisitionDelay_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_ADC_TemperatureAcquisitionDelay_CALLBACK)(int cmock_num_calls);
void ADC_TemperatureAcquisitionDelay_StubWithCallback(CMOCK_ADC_TemperatureAcquisitionDelay_CALLBACK Callback);

#endif
