/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockLED.h"

static const char* CMockString_LED_SetGreen = "LED_SetGreen";
static const char* CMockString_LED_SetOrange = "LED_SetOrange";
static const char* CMockString_on = "on";

typedef struct _CMOCK_LED_SetOrange_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int CallOrder;
  bool_t Expected_on;
  int IgnoreArg_on;

} CMOCK_LED_SetOrange_CALL_INSTANCE;

typedef struct _CMOCK_LED_SetGreen_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int CallOrder;
  bool_t Expected_on;
  int IgnoreArg_on;

} CMOCK_LED_SetGreen_CALL_INSTANCE;

static struct MockLEDInstance
{
  int LED_SetOrange_IgnoreBool;
  CMOCK_LED_SetOrange_CALLBACK LED_SetOrange_CallbackFunctionPointer;
  int LED_SetOrange_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE LED_SetOrange_CallInstance;
  int LED_SetGreen_IgnoreBool;
  CMOCK_LED_SetGreen_CALLBACK LED_SetGreen_CallbackFunctionPointer;
  int LED_SetGreen_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE LED_SetGreen_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void MockLED_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.LED_SetOrange_IgnoreBool)
    Mock.LED_SetOrange_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_LED_SetOrange);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.LED_SetOrange_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.LED_SetOrange_CallbackFunctionPointer != NULL)
    Mock.LED_SetOrange_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.LED_SetGreen_IgnoreBool)
    Mock.LED_SetGreen_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_LED_SetGreen);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.LED_SetGreen_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.LED_SetGreen_CallbackFunctionPointer != NULL)
    Mock.LED_SetGreen_CallInstance = CMOCK_GUTS_NONE;
}

void MockLED_Init(void)
{
  MockLED_Destroy();
}

void MockLED_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.LED_SetOrange_CallbackFunctionPointer = NULL;
  Mock.LED_SetOrange_CallbackCalls = 0;
  Mock.LED_SetGreen_CallbackFunctionPointer = NULL;
  Mock.LED_SetGreen_CallbackCalls = 0;
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void LED_SetOrange(bool_t on)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_LED_SetOrange);
  CMOCK_LED_SetOrange_CALL_INSTANCE* cmock_call_instance = (CMOCK_LED_SetOrange_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.LED_SetOrange_CallInstance);
  Mock.LED_SetOrange_CallInstance = CMock_Guts_MemNext(Mock.LED_SetOrange_CallInstance);
  if (Mock.LED_SetOrange_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.LED_SetOrange_CallbackFunctionPointer != NULL)
  {
    Mock.LED_SetOrange_CallbackFunctionPointer(on, Mock.LED_SetOrange_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_on)
  {
    UNITY_SET_DETAILS(CMockString_LED_SetOrange,CMockString_on);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_on, on, cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_LED_SetOrange(CMOCK_LED_SetOrange_CALL_INSTANCE* cmock_call_instance, bool_t on)
{
  cmock_call_instance->Expected_on = on;
  cmock_call_instance->IgnoreArg_on = 0;
}

void LED_SetOrange_CMockIgnore(void)
{
  Mock.LED_SetOrange_IgnoreBool = (int)1;
}

void LED_SetOrange_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_LED_SetOrange_CALL_INSTANCE));
  CMOCK_LED_SetOrange_CALL_INSTANCE* cmock_call_instance = (CMOCK_LED_SetOrange_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.LED_SetOrange_CallInstance = CMock_Guts_MemChain(Mock.LED_SetOrange_CallInstance, cmock_guts_index);
  Mock.LED_SetOrange_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void LED_SetOrange_CMockExpect(UNITY_LINE_TYPE cmock_line, bool_t on)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_LED_SetOrange_CALL_INSTANCE));
  CMOCK_LED_SetOrange_CALL_INSTANCE* cmock_call_instance = (CMOCK_LED_SetOrange_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.LED_SetOrange_CallInstance = CMock_Guts_MemChain(Mock.LED_SetOrange_CallInstance, cmock_guts_index);
  Mock.LED_SetOrange_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_LED_SetOrange(cmock_call_instance, on);
  UNITY_CLR_DETAILS();
}

void LED_SetOrange_StubWithCallback(CMOCK_LED_SetOrange_CALLBACK Callback)
{
  Mock.LED_SetOrange_CallbackFunctionPointer = Callback;
}

void LED_SetOrange_CMockIgnoreArg_on(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_LED_SetOrange_CALL_INSTANCE* cmock_call_instance = (CMOCK_LED_SetOrange_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.LED_SetOrange_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_on = 1;
}

void LED_SetGreen(bool_t on)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_LED_SetGreen);
  CMOCK_LED_SetGreen_CALL_INSTANCE* cmock_call_instance = (CMOCK_LED_SetGreen_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.LED_SetGreen_CallInstance);
  Mock.LED_SetGreen_CallInstance = CMock_Guts_MemNext(Mock.LED_SetGreen_CallInstance);
  if (Mock.LED_SetGreen_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (Mock.LED_SetGreen_CallbackFunctionPointer != NULL)
  {
    Mock.LED_SetGreen_CallbackFunctionPointer(on, Mock.LED_SetGreen_CallbackCalls++);
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  if (!cmock_call_instance->IgnoreArg_on)
  {
    UNITY_SET_DETAILS(CMockString_LED_SetGreen,CMockString_on);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_on, on, cmock_line, CMockStringMismatch);
  }

  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_LED_SetGreen(CMOCK_LED_SetGreen_CALL_INSTANCE* cmock_call_instance, bool_t on)
{
  cmock_call_instance->Expected_on = on;
  cmock_call_instance->IgnoreArg_on = 0;
}

void LED_SetGreen_CMockIgnore(void)
{
  Mock.LED_SetGreen_IgnoreBool = (int)1;
}

void LED_SetGreen_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_LED_SetGreen_CALL_INSTANCE));
  CMOCK_LED_SetGreen_CALL_INSTANCE* cmock_call_instance = (CMOCK_LED_SetGreen_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.LED_SetGreen_CallInstance = CMock_Guts_MemChain(Mock.LED_SetGreen_CallInstance, cmock_guts_index);
  Mock.LED_SetGreen_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void LED_SetGreen_CMockExpect(UNITY_LINE_TYPE cmock_line, bool_t on)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_LED_SetGreen_CALL_INSTANCE));
  CMOCK_LED_SetGreen_CALL_INSTANCE* cmock_call_instance = (CMOCK_LED_SetGreen_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.LED_SetGreen_CallInstance = CMock_Guts_MemChain(Mock.LED_SetGreen_CallInstance, cmock_guts_index);
  Mock.LED_SetGreen_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_LED_SetGreen(cmock_call_instance, on);
  UNITY_CLR_DETAILS();
}

void LED_SetGreen_StubWithCallback(CMOCK_LED_SetGreen_CALLBACK Callback)
{
  Mock.LED_SetGreen_CallbackFunctionPointer = Callback;
}

void LED_SetGreen_CMockIgnoreArg_on(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_LED_SetGreen_CALL_INSTANCE* cmock_call_instance = (CMOCK_LED_SetGreen_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.LED_SetGreen_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_on = 1;
}

